var playerData = [
{rank:"1",name:"Christian McCaffrey",team:"CAR",pos:"RB",min:"1",max:"1",stddev:"0",tier:"1",value:"High",notes:"",},
{rank:"2",name:"Saquon Barkley",team:"NYG",pos:"RB",min:"2",max:"2",stddev:"0",tier:"1",value:"High",notes:"",},
{rank:"3",name:"Ezekiel Elliott",team:"DAL",pos:"RB",min:"3",max:"5",stddev:"0.8",tier:"1",value:"High",notes:"Handcuff is Tony Pollard.",},
{rank:"4",name:"Alvin Kamara",team:"NO",pos:"RB",min:"3",max:"6",stddev:"1.02",tier:"1",value:"Good",notes:"Limited goal-line usage with Taysom Hill still stealing TDs.  Handcuff is Latavius Murray.",},
{rank:"5",name:"Derrick Henry",team:"TEN",pos:"RB",min:"5",max:"7",stddev:"0.75",tier:"2",value:"Good",notes:"Limited receiving production but high rushing workload.",},
{rank:"6",name:"Clyde Edwards-Helaire",team:"KC",pos:"RB",min:"4",max:"10",stddev:"1.94",tier:"2",value:"Good",notes:"Feature role with Damien Williams opted out of season.",},
{rank:"7",name:"Michael Thomas",team:"NO",pos:"WR",min:"4",max:"13",stddev:"3.19",tier:"1",value:"High",notes:"Very consistent.  Projections on par with top RBs.",},
{rank:"8",name:"Davante Adams",team:"GB",pos:"WR",min:"3",max:"12",stddev:"3.25",tier:"1",value:"High",notes:"Top target for Aaron Rodgers.",},
{rank:"9",name:"Dalvin Cook",team:"MIN",pos:"RB",min:"6",max:"11",stddev:"1.85",tier:"1",value:"Good",notes:"Injury concerns.  Handcuff is Mattison.",},
{rank:"10",name:"Tyreek Hill",team:"KC",pos:"WR",min:"8",max:"15",stddev:"2.58",tier:"1",value:"Good",notes:"",},
{rank:"11",name:"Joe Mixon",team:"CIN",pos:"RB",min:"7",max:"22",stddev:"5.46",tier:"2",value:"Low",notes:"Feature back, but low receiving production.",},
{rank:"12",name:"Julio Jones",team:"ATL",pos:"WR",min:"9",max:"15",stddev:"2.24",tier:"1",value:"Good",notes:"Low red-zone production.",},
{rank:"13",name:"Nick Chubb",team:"CLE",pos:"RB",min:"10",max:"17",stddev:"3.06",tier:"2",value:"Low",notes:"Will have competition from Kareem Hunt",},
{rank:"14",name:"George Kittle",team:"SF",pos:"TE",min:"11",max:"22",stddev:"3.72",tier:"1",value:"High",notes:"",},
{rank:"15",name:"Kenyan Drake",team:"ARI",pos:"RB",min:"9",max:"22",stddev:"4.26",tier:"2",value:"Good",notes:"High volume and production once traded to Arizona last season.",},
{rank:"16",name:"Miles Sanders",team:"PHI",pos:"RB",min:"12",max:"25",stddev:"5",tier:"2",value:"Good",notes:"Good offensive line.",},
{rank:"17",name:"Josh Jacobs",team:"LV",pos:"RB",min:"11",max:"27",stddev:"6.24",tier:"2",value:"Moderate",notes:"",},
{rank:"18",name:"Travis Kelce",team:"KC",pos:"TE",min:"13",max:"21",stddev:"2.94",tier:"1",value:"High",notes:"",},
{rank:"19",name:"Austin Ekeler",team:"LAC",pos:"RB",min:"12",max:"25",stddev:"5.31",tier:"2",value:"Moderate",notes:"Good production last year behind Melvin Gordon, who's now gone.  Step down at QB may hurt 3rd down role?",},
{rank:"20",name:"Aaron Jones",team:"GB",pos:"RB",min:"16",max:"26",stddev:"3.63",tier:"2",value:"Good",notes:"#2 fantasy RB last year.",},
{rank:"21",name:"DeAndre Hopkins",team:"ARI",pos:"WR",min:"14",max:"31",stddev:"6.47",tier:"1",value:"Moderate",notes:"Working with new QB.  Should have lots of targets in aggressive offense.",},
{rank:"22",name:"Allen Robinson",team:"CHI",pos:"WR",min:"13",max:"30",stddev:"5.98",tier:"2",value:"Good",notes:"QB position unsettled.",},
{rank:"23",name:"James Conner",team:"PIT",pos:"RB",min:"18",max:"29",stddev:"4.07",tier:"3",value:"Good",notes:"Good production until injury halfway through last season.",},
{rank:"24",name:"Chris Godwin",team:"TB",pos:"WR",min:"20",max:"47",stddev:"10.71",tier:"2",value:"Good",notes:"Sharing targets with Mike Evans.  Step up at QB with Brady.",},
{rank:"25",name:"Patrick Mahomes",team:"KC",pos:"QB",min:"18",max:"32",stddev:"5.19",tier:"1",value:"Good",notes:"",},
{rank:"26",name:"Adam Thielen",team:"MIN",pos:"WR",min:"17",max:"33",stddev:"5.54",tier:"2",value:"Good",notes:"Run-heavy offense, but clear top WR with Stefon Diggs gone.",},
{rank:"27",name:"Kenny Golladay",team:"DET",pos:"WR",min:"25",max:"36",stddev:"3.52",tier:"2",value:"High",notes:"Good red zone potential.  Stafford's top weapon.",},
{rank:"28",name:"Chris Carson",team:"SEA",pos:"RB",min:"26",max:"41",stddev:"5.49",tier:"2",value:"Moderate",notes:"Good volume.  Competition from Rashaad Penny.",},
{rank:"29",name:"Lamar Jackson",team:"BAL",pos:"QB",min:"26",max:"36",stddev:"3.5",tier:"1",value:"Good",notes:"",},
{rank:"30",name:"Melvin Gordon",team:"DEN",pos:"RB",min:"26",max:"40",stddev:"4.73",tier:"3",value:"Good",notes:"Will share carries with Philip Lindsay, but offense should run a lot.",},
{rank:"31",name:"Jonathan Taylor",team:"IND",pos:"RB",min:"19",max:"50",stddev:"9.98",tier:"3",value:"Moderate",notes:"Rookie.  Some concerns with fumbles and receiving abaility.  Draft to stash on bench.",},
{rank:"32",name:"Mike Evans",team:"TB",pos:"WR",min:"20",max:"59",stddev:"13.25",tier:"2",value:"Moderate",notes:"Sharing targets with Chris Godwin.  Step up at QB with Brady.  Good red zone potential.",},
{rank:"33",name:"D.J. Moore",team:"CAR",pos:"WR",min:"24",max:"41",stddev:"5.78",tier:"2",value:"Good",notes:"New QB.",},
{rank:"34",name:"A.J. Brown",team:"TEN",pos:"WR",min:"20",max:"44",stddev:"8.42",tier:"2",value:"Moderate",notes:"Boom-and-bust but best option in TEN",},
{rank:"35",name:"Odell Beckham Jr.",team:"CLE",pos:"WR",min:"23",max:"68",stddev:"16.76",tier:"2",value:"Moderate",notes:"Frustrating last year with injuries and poor QB play",},
{rank:"36",name:"Mark Ingram II",team:"BAL",pos:"RB",min:"21",max:"64",stddev:"14.84",tier:"3",value:"Low",notes:"Highly TD-dependent last season.  Now facing rookie JK Dobbins",},
{rank:"37",name:"JuJu Smith-Schuster",team:"PIT",pos:"WR",min:"29",max:"50",stddev:"6.83",tier:"2",value:"Good",notes:"Bounce-back candidate with Roethlisberger returning",},
{rank:"38",name:"Todd Gurley",team:"ATL",pos:"RB",min:"30",max:"62",stddev:"11.07",tier:"3",value:"Moderate",notes:"Injury concerns.",},
{rank:"39",name:"Mark Andrews",team:"BAL",pos:"TE",min:"34",max:"49",stddev:"5.14",tier:"2",value:"",notes:"",},
{rank:"40",name:"Terry McLaurin",team:"WAS",pos:"WR",min:"23",max:"74",stddev:"17.5",tier:"3",value:"Good",notes:"",},
{rank:"41",name:"Cooper Kupp",team:"LAR",pos:"WR",min:"31",max:"53",stddev:"7.4",tier:"2",value:"Low",notes:"Saw dropoff in usage last quarter of the season",},
{rank:"42",name:"Amari Cooper",team:"DAL",pos:"WR",min:"36",max:"54",stddev:"7.89",tier:"2",value:"Moderate",notes:"",},
{rank:"43",name:"Zach Ertz",team:"PHI",pos:"TE",min:"43",max:"48",stddev:"2.15",tier:"2",value:"",notes:"",},
{rank:"44",name:"Raheem Mostert",team:"SF",pos:"RB",min:"38",max:"57",stddev:"6.79",tier:"3",value:"Good",notes:"Limited receiving role.",},
{rank:"45",name:"David Johnson",team:"HOU",pos:"RB",min:"37",max:"65",stddev:"10.35",tier:"3",value:"Moderate",notes:"Top of the depth chart, but likely to cede 3rd downs to Duke Johnson.",},
{rank:"46",name:"Tyler Lockett",team:"SEA",pos:"WR",min:"31",max:"67",stddev:"13.84",tier:"2",value:"Good",notes:"Top receiver in Seattle",},
{rank:"47",name:"Le'Veon Bell",team:"NYJ",pos:"RB",min:"35",max:"72",stddev:"12.58",tier:"3",value:"Moderate",notes:"High volume and improved offensive line, but low ceiling.",},
{rank:"48",name:"D'Andre Swift",team:"DET",pos:"RB",min:"42",max:"55",stddev:"4.62",tier:"3",value:"Moderate",notes:"Rookie out of Georgia.  Will play behind Kerryon Johnson, probably as 3rd down back.",},
{rank:"49",name:"Cam Akers",team:"LAR",pos:"RB",min:"28",max:"69",stddev:"14.13",tier:"3",value:"Moderate",notes:"Rookie out of Florida State.  In open competition to replace Todd Gurley.",},
{rank:"50",name:"D.J. Chark",team:"JAC",pos:"WR",min:"27",max:"83",stddev:"19.65",tier:"3",value:"Moderate",notes:"Good production last year on a bad offense, which may improve",},
{rank:"51",name:"Calvin Ridley",team:"ATL",pos:"WR",min:"36",max:"82",stddev:"16.18",tier:"2",value:"Moderate",notes:"Good consistency",},
{rank:"52",name:"Kareem Hunt",team:"CLE",pos:"RB",min:"51",max:"56",stddev:"1.72",tier:"3",value:"Good",notes:"Will split time with Nick Chubb.",},
{rank:"53",name:"Dak Prescott",team:"DAL",pos:"QB",min:"46",max:"59",stddev:"4.45",tier:"2",value:"Moderate",notes:"",},
{rank:"54",name:"Russell Wilson",team:"SEA",pos:"QB",min:"52",max:"68",stddev:"5.71",tier:"2",value:"Good",notes:"",},
{rank:"55",name:"D.K. Metcalf",team:"SEA",pos:"WR",min:"35",max:"76",stddev:"13.18",tier:"3",value:"Good",notes:"Led league in red zone targets.  Boom-or-bust performances last year",},
{rank:"56",name:"Courtland Sutton",team:"DEN",pos:"WR",min:"39",max:"91",stddev:"19.47",tier:"2",value:"Moderate",notes:"More competition this year, but good after the catch",},
{rank:"57",name:"Ronald Jones II",team:"TB",pos:"RB",min:"43",max:"76",stddev:"11.41",tier:"3",value:"Low",notes:"Now competing with Leonard Fournette",},
{rank:"58",name:"Tyler Higbee",team:"LAR",pos:"TE",min:"49",max:"76",stddev:"10.97",tier:"3",value:"",notes:"",},
{rank:"59",name:"Kyler Murray",team:"ARI",pos:"QB",min:"57",max:"65",stddev:"2.71",tier:"2",value:"Good",notes:"",},
{rank:"60",name:"Keenan Allen",team:"LAC",pos:"WR",min:"40",max:"87",stddev:"19.65",tier:"3",value:"Low",notes:"New QB",},
{rank:"61",name:"Robert Woods",team:"LAR",pos:"WR",min:"45",max:"72",stddev:"9.88",tier:"2",value:"Moderate",notes:"Good yardage, low TDs",},
{rank:"62",name:"Deshaun Watson",team:"HOU",pos:"QB",min:"64",max:"71",stddev:"2.28",tier:"2",value:"Moderate",notes:"",},
{rank:"63",name:"T.Y. Hilton",team:"IND",pos:"WR",min:"46",max:"93",stddev:"15.61",tier:"3",value:"Good",notes:"Should bounce back with Rivers",},
{rank:"64",name:"Marquise Brown",team:"BAL",pos:"WR",min:"39",max:"102",stddev:"20.53",tier:"4",value:"Good",notes:"Boom-and-bust but big-play potential",},
{rank:"65",name:"DeVante Parker",team:"MIA",pos:"WR",min:"64",max:"87",stddev:"8.12",tier:"3",value:"Good",notes:"Big season last year after a history of injuries",},
{rank:"66",name:"Michael Gallup",team:"DAL",pos:"WR",min:"58",max:"103",stddev:"16.49",tier:"4",value:"Good",notes:"Competing with Amari Cooper and CeeDee Lamb, but a favorite target for Dak Prescott",},
{rank:"67",name:"Matt Ryan",team:"ATL",pos:"QB",min:"62",max:"83",stddev:"7.28",tier:"3",value:"",notes:"",},
{rank:"68",name:"Jordan Howard",team:"MIA",pos:"RB",min:"50",max:"106",stddev:"19.82",tier:"4",value:"Good",notes:"In competition with Matt Breida.  Limited receiving role.",},
{rank:"69",name:"Jared Cook",team:"NO",pos:"TE",min:"59",max:"97",stddev:"15.55",tier:"3",value:"",notes:"",},
{rank:"70",name:"J.K. Dobbins",team:"BAL",pos:"RB",min:"51",max:"110",stddev:"20.13",tier:"4",value:"Good",notes:"Expected to take lead back role over Ingraham",},
{rank:"71",name:"Josh Allen",team:"BUF",pos:"QB",min:"60",max:"104",stddev:"16.5",tier:"3",value:"",notes:"",},
{rank:"72",name:"Stefon Diggs",team:"BUF",pos:"WR",min:"62",max:"95",stddev:"11.99",tier:"4",value:"Low",notes:"Likely to dropoff in move to Buffalo",},
{rank:"73",name:"Matt Breida",team:"MIA",pos:"RB",min:"70",max:"94",stddev:"8.26",tier:"4",value:"Good",notes:"In competition with Jordan Howard.",},
{rank:"74",name:"Zack Moss",team:"BUF",pos:"RB",min:"61",max:"100",stddev:"12.51",tier:"4",value:"Good",notes:"Rookie out of Utah.  Will compete with Devin Singletary.  Likely to get goal-line work.",},
{rank:"75",name:"Drew Brees",team:"NO",pos:"QB",min:"70",max:"92",stddev:"8.26",tier:"3",value:"",notes:"",},
{rank:"76",name:"Tyler Boyd",team:"CIN",pos:"WR",min:"69",max:"95",stddev:"8.71",tier:"4",value:"Moderate",notes:"Slot receiver with rookie QB Joe Burrow.  More competition this year with AJ Green returning",},
{rank:"77",name:"Hunter Henry",team:"LAC",pos:"TE",min:"59",max:"115",stddev:"25.48",tier:"3",value:"",notes:"",},
{rank:"78",name:"Will Fuller",team:"HOU",pos:"WR",min:"66",max:"107",stddev:"13.64",tier:"4",value:"Good",notes:"Role will increase with DeAndre Hopkins gone.  Long injury history.",},
{rank:"79",name:"Matthew Stafford",team:"DET",pos:"QB",min:"64",max:"101",stddev:"13.46",tier:"3",value:"",notes:"",},
{rank:"80",name:"David Montgomery",team:"CHI",pos:"RB",min:"42",max:"146",stddev:"41.81",tier:"3",value:"Moderate",notes:"Splits time with Tarik Cohen.",},
{rank:"81",name:"Jarvis Landry",team:"CLE",pos:"WR",min:"81",max:"94",stddev:"4.45",tier:"3",value:"",notes:"",},
{rank:"82",name:"Carson Wentz",team:"PHI",pos:"QB",min:"72",max:"110",stddev:"15.47",tier:"3",value:"",notes:"",},
{rank:"83",name:"A.J. Green",team:"CIN",pos:"WR",min:"61",max:"119",stddev:"19.03",tier:"4",value:"Good",notes:"Returning from injury and with rookie QB Joe Burrow, but high upside",},
{rank:"84",name:"Diontae Johnson",team:"PIT",pos:"WR",min:"82",max:"115",stddev:"11.45",tier:"5",value:"Good",notes:"Good rookie season last year without Roethlisburger.  Lot of competition",},
{rank:"85",name:"Marvin Jones",team:"DET",pos:"WR",min:"68",max:"124",stddev:"20.17",tier:"5",value:"High",notes:"Similar number of targets as Golladay",},
{rank:"86",name:"Devin Singletary",team:"BUF",pos:"RB",min:"45",max:"67",stddev:"7.98",tier:"3",value:"Moderate",notes:"Small size means limited goal line work.  Some injury concerns.",},
{rank:"87",name:"Julian Edelman",team:"NE",pos:"WR",min:"71",max:"123",stddev:"18.31",tier:"5",value:"Good",notes:"Dropoff expected without Brady",},
{rank:"88",name:"Jamison Crowder",team:"NYJ",pos:"WR",min:"80",max:"112",stddev:"10.32",tier:"5",value:"Moderate",notes:"Slot receiver.  High targets, limited TDs",},
{rank:"89",name:"Ben Roethlisberger",team:"PIT",pos:"QB",min:"81",max:"115",stddev:"11.53",tier:"3",value:"",notes:"",},
{rank:"90",name:"Darren Waller",team:"LV",pos:"TE",min:"46",max:"185",stddev:"50.6",tier:"2",value:"",notes:"",},
{rank:"91",name:"Tom Brady",team:"TB",pos:"QB",min:"87",max:"137",stddev:"18.8",tier:"3",value:"",notes:"",},
{rank:"92",name:"Antonio Gibson",team:"WAS",pos:"RB",min:"58",max:"145",stddev:"27.53",tier:"4",value:"Good",notes:"Rookie out of Memphis.  High upside.",},
{rank:"93",name:"Leonard Fournette",team:"TB",pos:"RB",min:"45",max:"87",stddev:"20.02",tier:"2",value:"Good",notes:"Signed with TB",},
{rank:"94",name:"Hayden Hurst",team:"ATL",pos:"TE",min:"57",max:"157",stddev:"36.06",tier:"3",value:"",notes:"",},
{rank:"95",name:"Evan Engram",team:"NYG",pos:"TE",min:"67",max:"207",stddev:"51.04",tier:"3",value:"",notes:"",},
{rank:"96",name:"Latavius Murray",team:"NO",pos:"RB",min:"75",max:"142",stddev:"21.25",tier:"4",value:"Moderate",notes:"Handcuff for Alvin Kamara",},
{rank:"97",name:"James White",team:"NE",pos:"RB",min:"51",max:"88",stddev:"13.65",tier:"4",value:"Moderate",notes:"Less valuable with Tom Brady gone.",},
{rank:"98",name:"Sterling Shepard",team:"NYG",pos:"WR",min:"90",max:"150",stddev:"21.53",tier:"5",value:"Good",notes:"High number of targets last year.  Competition from Tate and Slayton",},
{rank:"99",name:"John Brown",team:"BUF",pos:"WR",min:"93",max:"132",stddev:"12.56",tier:"5",value:"Moderate",notes:"Run-first scheme.  Competition from Stefon Diggs",},
{rank:"100",name:"Jared Goff",team:"LAR",pos:"QB",min:"92",max:"149",stddev:"20.29",tier:"4",value:"",notes:"",},
{rank:"101",name:"Damien Harris",team:"NE",pos:"RB",min:"69",max:"153",stddev:"27.65",tier:"6",value:"Low",notes:"Crowded backfield in NE, but most upside after James White.",},
{rank:"102",name:"Darius Slayton",team:"NYG",pos:"WR",min:"85",max:"129",stddev:"14.55",tier:"5",value:"Good",notes:"More upside thanTate and Shepard",},
{rank:"103",name:"Daniel Jones",team:"NYG",pos:"QB",min:"82",max:"145",stddev:"21.29",tier:"3",value:"",notes:"",},
{rank:"104",name:"Aaron Rodgers",team:"GB",pos:"QB",min:"87",max:"146",stddev:"22.01",tier:"3",value:"",notes:"",},
{rank:"105",name:"Phillip Lindsay",team:"DEN",pos:"RB",min:"58",max:"94",stddev:"13.8",tier:"4",value:"Moderate",notes:"Role reduced by addition of Melvin Gordon.",},
{rank:"106",name:"Brandin Cooks",team:"HOU",pos:"WR",min:"93",max:"136",stddev:"14.82",tier:"5",value:"Good",notes:"New team, taking place of DeAndre Hopkins.  Will compete with Will Fuller and Randall Cobb for targets",},
{rank:"107",name:"Baker Mayfield",team:"CLE",pos:"QB",min:"99",max:"142",stddev:"14.46",tier:"4",value:"",notes:"",},
{rank:"108",name:"Tevin Coleman",team:"SF",pos:"RB",min:"63",max:"111",stddev:"17.84",tier:"4",value:"Low",notes:"3rd down back.  Competing with Raheem Mostert and Jerick McKinnon",},
{rank:"109",name:"Christian Kirk",team:"ARI",pos:"WR",min:"103",max:"131",stddev:"9.91",tier:"5",value:"Moderate",notes:"Likely dropoff with arrival of DeAndre Hopkins",},
{rank:"110",name:"Mike Williams",team:"LAC",pos:"WR",min:"101",max:"135",stddev:"13.06",tier:"6",value:"Moderate",notes:"Dropoff in QB",},
{rank:"111",name:"Emmanuel Sanders",team:"NO",pos:"WR",min:"100",max:"133",stddev:"12.6",tier:"5",value:"Good",notes:"Older but consistent.  Moving to better offense in NO",},
{rank:"112",name:"Anthony Miller",team:"CHI",pos:"WR",min:"97",max:"151",stddev:"17.29",tier:"7",value:"Moderate",notes:"Slot receiver.  Low upside but little serious competition",},
{rank:"113",name:"Tarik Cohen",team:"CHI",pos:"RB",min:"52",max:"119",stddev:"24.42",tier:"4",value:"Good",notes:"Splits time with David Montgomery.",},
{rank:"114",name:"Joe Burrow",team:"CIN",pos:"QB",min:"86",max:"197",stddev:"39.65",tier:"",value:"",notes:"",},
{rank:"115",name:"Rob Gronkowski",team:"TB",pos:"TE",min:"77",max:"211",stddev:"46.06",tier:"3",value:"",notes:"",},
{rank:"116",name:"Cam Newton",team:"NE",pos:"QB",min:"95",max:"186",stddev:"31.96",tier:"4",value:"",notes:"",},
{rank:"117",name:"Ryan Tannehill",team:"TEN",pos:"QB",min:"102",max:"139",stddev:"15.5",tier:"4",value:"",notes:"",},
{rank:"118",name:"San Francisco 49ers",team:"SF",pos:"DST",min:"120",max:"149",stddev:"11.09",tier:"1",value:"",notes:"",},
{rank:"119",name:"Deebo Samuel",team:"SF",pos:"WR",min:"116",max:"162",stddev:"16.23",tier:"4",value:"Moderate",notes:"Slot receiver.  Recovering from foot injury",},
{rank:"120",name:"Mike Gesicki",team:"MIA",pos:"TE",min:"71",max:"167",stddev:"38.58",tier:"5",value:"",notes:"",},
{rank:"121",name:"CeeDee Lamb",team:"DAL",pos:"WR",min:"73",max:"184",stddev:"42.16",tier:"6",value:"Good",notes:"Rookie out of Oklahoma.  Behind Cooper and Gallup.",},
{rank:"122",name:"Curtis Samuel",team:"CAR",pos:"WR",min:"120",max:"144",stddev:"8.98",tier:"5",value:"Moderate",notes:"Likely losing targets to Robby Anderson",},
{rank:"123",name:"Marlon Mack",team:"IND",pos:"RB",min:"79",max:"143",stddev:"23.44",tier:"5",value:"Moderate",notes:"Expected to share carries with Jonathan Taylor",},
{rank:"124",name:"Blake Jarwin",team:"DAL",pos:"TE",min:"85",max:"231",stddev:"52.85",tier:"",value:"",notes:"",},
{rank:"125",name:"Adrian Peterson",team:"DET",pos:"RB",min:"69",max:"172",stddev:"40.35",tier:"6",value:"Moderate",notes:"Signed with Lions",},
{rank:"126",name:"Austin Hooper",team:"CLE",pos:"TE",min:"90",max:"229",stddev:"47.4",tier:"5",value:"",notes:"",},
{rank:"127",name:"Golden Tate",team:"NYG",pos:"WR",min:"118",max:"171",stddev:"19.91",tier:"5",value:"Moderate",notes:"Now in NYG.  Competition from Slayton and Shepard.  Expect yards but not TDs",},
{rank:"128",name:"Duke Johnson",team:"HOU",pos:"RB",min:"114",max:"205",stddev:"34.2",tier:"5",value:"Moderate",notes:"3rd down back with low ceiling.  Behind David Johnson.",},
{rank:"129",name:"Mecole Hardman",team:"KC",pos:"WR",min:"126",max:"161",stddev:"12.18",tier:"6",value:"Moderate",notes:"Good upside, but low on depth chart.  Probably limited use early in season",},
{rank:"130",name:"Tony Pollard",team:"DAL",pos:"RB",min:"117",max:"159",stddev:"16.83",tier:"4",value:"Low",notes:"Handcuff for Ezekiel Elliott.",},
{rank:"131",name:"T.J. Hockenson",team:"DET",pos:"TE",min:"83",max:"232",stddev:"48.58",tier:"3",value:"",notes:"",},
{rank:"132",name:"Darrell Henderson",team:"LAR",pos:"RB",min:"81",max:"161",stddev:"32.76",tier:"4",value:"Low",notes:"Likely behind Cam Akers.",},
{rank:"133",name:"Noah Fant",team:"DEN",pos:"TE",min:"109",max:"236",stddev:"47.58",tier:"3",value:"",notes:"",},
{rank:"134",name:"Dallas Goedert",team:"PHI",pos:"TE",min:"113",max:"131",stddev:"7.28",tier:"",value:"",notes:"",},
{rank:"135",name:"Kerryon Johnson",team:"DET",pos:"RB",min:"109",max:"146",stddev:"14.77",tier:"4",value:"Moderate",notes:"Injury history.  Facing competition from D'Andre Swift.",},
{rank:"136",name:"Chris Herndon IV",team:"NYJ",pos:"TE",min:"92",max:"175",stddev:"33.86",tier:"5",value:"",notes:"",},
{rank:"137",name:"Alexander Mattison",team:"MIN",pos:"RB",min:"109",max:"140",stddev:"14.77",tier:"4",value:"Moderate",notes:"Handcuff for Dalvin Cook",},
{rank:"138",name:"Preston Williams",team:"MIA",pos:"WR",min:"110",max:"189",stddev:"27.34",tier:"5",value:"",notes:"",},
{rank:"139",name:"Kirk Cousins",team:"MIN",pos:"QB",min:"118",max:"134",stddev:"7.09",tier:"",value:"",notes:"",},
{rank:"140",name:"Baltimore Ravens",team:"BAL",pos:"DST",min:"118",max:"140",stddev:"7.82",tier:"1",value:"",notes:"",},
{rank:"141",name:"Chicago Bears",team:"CHI",pos:"DST",min:"141",max:"169",stddev:"10.7",tier:"2",value:"",notes:"",},
{rank:"142",name:"Pittsburgh Steelers",team:"PIT",pos:"DST",min:"123",max:"147",stddev:"8.97",tier:"1",value:"",notes:"",},
{rank:"143",name:"Jonnu Smith",team:"TEN",pos:"TE",min:"104",max:"220",stddev:"49.15",tier:"",value:"",notes:"",},
{rank:"144",name:"Jimmy Garoppolo",team:"SF",pos:"QB",min:"101",max:"162",stddev:"22.26",tier:"4",value:"",notes:"",},
{rank:"145",name:"Justin Jefferson",team:"MIN",pos:"WR",min:"89",max:"183",stddev:"35.24",tier:"6",value:"Good",notes:"Rookie.  Effectively replacing Stefon Diggs",},
{rank:"146",name:"Jerry Jeudy",team:"DEN",pos:"WR",min:"101",max:"181",stddev:"28.54",tier:"6",value:"High",notes:"Rookie from Alabama.  Expected to have every-down role immediately.  QB Lock unproven",},
{rank:"147",name:"DeSean Jackson",team:"PHI",pos:"WR",min:"98",max:"223",stddev:"52.39",tier:"6",value:"Moderate",notes:"Potential, but long injury history",},
{rank:"148",name:"Sam Darnold",team:"NYJ",pos:"QB",min:"110",max:"178",stddev:"31",tier:"",value:"",notes:"",},
{rank:"149",name:"Chase Edmonds",team:"ARI",pos:"RB",min:"75",max:"188",stddev:"43.21",tier:"6",value:"Moderate",notes:"Primary backup to Kenyan Drake",},
{rank:"150",name:"Breshad Perriman",team:"NYJ",pos:"WR",min:"106",max:"174",stddev:"24.26",tier:"6",value:"Good",notes:"Role likely to increase",},
{rank:"151",name:"Jalen Reagor",team:"PHI",pos:"WR",min:"121",max:"187",stddev:"25.82",tier:"6",value:"Good",notes:"Rookie.  Could have large role if Alshon Jeffery is injured",},
{rank:"152",name:"Boston Scott",team:"PHI",pos:"RB",min:"116",max:"184",stddev:"26.87",tier:"6",value:"Moderate",notes:"Receiving back.  Behind Miles Sanders",},
{rank:"153",name:"Brandon Aiyuk",team:"SF",pos:"WR",min:"125",max:"199",stddev:"32.94",tier:"7",value:"Moderate",notes:"Likely low usage in SF offense",},
{rank:"154",name:"Teddy Bridgewater",team:"CAR",pos:"QB",min:"126",max:"157",stddev:"12.75",tier:"",value:"",notes:"",},
{rank:"155",name:"Buffalo Bills",team:"BUF",pos:"DST",min:"135",max:"163",stddev:"11.11",tier:"1",value:"",notes:"",},
{rank:"156",name:"Ke'Shawn Vaughn",team:"TB",pos:"RB",min:"71",max:"151",stddev:"33.63",tier:"5",value:"Low",notes:"Now behind Fournette and Ronald Jones",},
{rank:"157",name:"Parris Campbell",team:"IND",pos:"WR",min:"124",max:"217",stddev:"34.4",tier:"6",value:"Good",notes:"Lost most of rookie season to injury.  Likely to be second in targets behind Hilton",},
{rank:"158",name:"Justin Tucker",team:"BAL",pos:"K",min:"145",max:"166",stddev:"8.35",tier:"1",value:"",notes:"",},
{rank:"159",name:"Minnesota Vikings",team:"MIN",pos:"DST",min:"142",max:"171",stddev:"11.34",tier:"3",value:"",notes:"",},
{rank:"160",name:"Philip Rivers",team:"IND",pos:"QB",min:"130",max:"173",stddev:"16.92",tier:"",value:"",notes:"",},
{rank:"161",name:"New Orleans Saints",team:"NO",pos:"DST",min:"139",max:"196",stddev:"23.89",tier:"3",value:"",notes:"",},
{rank:"162",name:"Henry Ruggs III",team:"LV",pos:"WR",min:"90",max:"198",stddev:"40.08",tier:"7",value:"",notes:"Raiders thin at receiver.  Likely big-lay dependent",},
{rank:"163",name:"Derek Carr",team:"LV",pos:"QB",min:"127",max:"211",stddev:"32.9",tier:"",value:"",notes:"",},
{rank:"164",name:"Harrison Butker",team:"KC",pos:"K",min:"152",max:"174",stddev:"8.64",tier:"1",value:"",notes:"",},
{rank:"165",name:"Nyheim Hines",team:"IND",pos:"RB",min:"119",max:"202",stddev:"38.85",tier:"5",value:"Moderate",notes:"3rd down back.",},
{rank:"166",name:"Kansas City Chiefs",team:"KC",pos:"DST",min:"152",max:"179",stddev:"10.84",tier:"",value:"",notes:"",},
{rank:"167",name:"Gardner Minshew II",team:"JAC",pos:"QB",min:"108",max:"248",stddev:"54.12",tier:"",value:"",notes:"",},
{rank:"168",name:"Wil Lutz",team:"NO",pos:"K",min:"158",max:"178",stddev:"8.26",tier:"1",value:"",notes:"",},
{rank:"169",name:"Sony Michel",team:"NE",pos:"RB",min:"112",max:"165",stddev:"21.65",tier:"",value:"",notes:"",},
{rank:"170",name:"Allen Lazard",team:"GB",pos:"WR",min:"129",max:"205",stddev:"32.78",tier:"7",value:"",notes:"",},
{rank:"171",name:"Greg Zuerlein",team:"DAL",pos:"K",min:"154",max:"187",stddev:"11.97",tier:"2",value:"",notes:"",},
{rank:"172",name:"DeAndre Washington",team:"KC",pos:"RB",min:"132",max:"159",stddev:"11.44",tier:"",value:"",notes:"",},
{rank:"173",name:"Laviska Shenault Jr.",team:"JAC",pos:"WR",min:"131",max:"190",stddev:"23.14",tier:"",value:"",notes:"",},
{rank:"174",name:"Jack Doyle",team:"IND",pos:"TE",min:"120",max:"168",stddev:"19.65",tier:"5",value:"",notes:"",},
{rank:"175",name:"Greg Olsen",team:"SEA",pos:"TE",min:"134",max:"153",stddev:"8.18",tier:"",value:"",notes:"",},
{rank:"176",name:"Eric Ebron",team:"PIT",pos:"TE",min:"119",max:"163",stddev:"19.67",tier:"5",value:"",notes:"",},
{rank:"177",name:"New England Patriots",team:"NE",pos:"DST",min:"134",max:"202",stddev:"24.42",tier:"2",value:"",notes:"",},
{rank:"178",name:"James Washington",team:"PIT",pos:"WR",min:"136",max:"204",stddev:"26.62",tier:"",value:"",notes:"",},
{rank:"179",name:"Drew Lock",team:"DEN",pos:"QB",min:"148",max:"269",stddev:"51.68",tier:"",value:"",notes:"",},
{rank:"180",name:"Justin Jackson",team:"LAC",pos:"RB",min:"122",max:"213",stddev:"40.94",tier:"5",value:"Moderate",notes:"Competing with Joshua Kelley for spot behind Austin Ekeler.  More upside.",},
{rank:"181",name:"Denver Broncos",team:"DEN",pos:"DST",min:"141",max:"208",stddev:"24.24",tier:"2",value:"",notes:"",},
{rank:"182",name:"Robby Anderson",team:"CAR",pos:"WR",min:"152",max:"165",stddev:"5.35",tier:"5",value:"Low",notes:"Now in Carolina, but with lots of competition for targets.",},
{rank:"183",name:"Ian Thomas",team:"CAR",pos:"TE",min:"136",max:"204",stddev:"31.37",tier:"",value:"",notes:"",},
{rank:"184",name:"Sammy Watkins",team:"KC",pos:"WR",min:"133",max:"179",stddev:"19.91",tier:"7",value:"Moderate",notes:"Inconsistent but in an explosive offense",},
{rank:"185",name:"Matt Prater",team:"DET",pos:"K",min:"170",max:"199",stddev:"12.82",tier:"1",value:"",notes:"",},
{rank:"186",name:"Philadelphia Eagles",team:"PHI",pos:"DST",min:"168",max:"195",stddev:"12.38",tier:"",value:"",notes:"",},
{rank:"187",name:"Robbie Gould",team:"SF",pos:"K",min:"165",max:"210",stddev:"16.48",tier:"2",value:"",notes:"",},
{rank:"188",name:"Los Angeles Rams",team:"LAR",pos:"DST",min:"159",max:"177",stddev:"8.26",tier:"",value:"",notes:"",},
{rank:"189",name:"N'Keal Harry",team:"NE",pos:"WR",min:"130",max:"197",stddev:"30.27",tier:"7",value:"Good",notes:"Little competition for targets other than Edelman.  QB quality unknown",},
{rank:"190",name:"O.J. Howard",team:"TB",pos:"TE",min:"130",max:"196",stddev:"30.88",tier:"",value:"",notes:"",},
{rank:"191",name:"Zane Gonzalez",team:"ARI",pos:"K",min:"174",max:"219",stddev:"16.89",tier:"3",value:"",notes:"",},
{rank:"192",name:"Dallas Cowboys",team:"DAL",pos:"DST",min:"140",max:"244",stddev:"40.74",tier:"",value:"",notes:"",},
{rank:"193",name:"Ryan Fitzpatrick",team:"MIA",pos:"QB",min:"153",max:"228",stddev:"26.92",tier:"",value:"",notes:"",},
{rank:"194",name:"Los Angeles Chargers",team:"LAC",pos:"DST",min:"168",max:"228",stddev:"22.79",tier:"3",value:"",notes:"",},
{rank:"195",name:"Jace Sternberger",team:"GB",pos:"TE",min:"137",max:"156",stddev:"9.5",tier:"",value:"",notes:"",},
{rank:"196",name:"Irv Smith Jr.",team:"MIN",pos:"TE",min:"138",max:"249",stddev:"48.64",tier:"",value:"",notes:"",},
{rank:"197",name:"Tennessee Titans",team:"TEN",pos:"DST",min:"167",max:"229",stddev:"22.55",tier:"",value:"",notes:"",},
{rank:"198",name:"Hunter Renfrow",team:"LV",pos:"WR",min:"165",max:"211",stddev:"20.24",tier:"",value:"",notes:"",},
{rank:"199",name:"Jake Elliott",team:"PHI",pos:"K",min:"178",max:"233",stddev:"22.79",tier:"3",value:"",notes:"",},
{rank:"200",name:"Michael Pittman Jr.",team:"IND",pos:"WR",min:"141",max:"163",stddev:"11",tier:"7",value:"Moderate",notes:"Physical.  Could be WR3 in Indy soon",},
{rank:"201",name:"A.J. Dillon",team:"GB",pos:"RB",min:"148",max:"226",stddev:"32.01",tier:"7",value:"Moderate",notes:"Big size.  Behind Aaron Jones and Jamaal Williams.",},
{rank:"202",name:"Dawson Knox",team:"BUF",pos:"TE",min:"175",max:"199",stddev:"9.81",tier:"",value:"",notes:"",},
{rank:"203",name:"Bryan Edwards",team:"LV",pos:"WR",min:"149",max:"164",stddev:"7.5",tier:"",value:"",notes:"",},
{rank:"204",name:"Seattle Seahawks",team:"SEA",pos:"DST",min:"177",max:"225",stddev:"17.17",tier:"",value:"",notes:"",},
{rank:"205",name:"Tyrod Taylor",team:"LAC",pos:"QB",min:"169",max:"235",stddev:"24.05",tier:"",value:"",notes:"",},
{rank:"206",name:"Ryquell Armstead",team:"JAC",pos:"RB",min:"84",max:"277",stddev:"96.5",tier:"5",value:"Good",notes:"Competing for lead back.  On COVID list.",},
{rank:"207",name:"Alshon Jeffery",team:"PHI",pos:"WR",min:"181",max:"218",stddev:"16.78",tier:"",value:"",notes:"",},
{rank:"208",name:"Larry Fitzgerald",team:"ARI",pos:"WR",min:"174",max:"209",stddev:"14.97",tier:"7",value:"Moderate",notes:"Limited to a slot receiver these days",},
{rank:"209",name:"Dan Bailey",team:"MIN",pos:"K",min:"172",max:"245",stddev:"28.33",tier:"",value:"",notes:"",},
{rank:"210",name:"Carlos Hyde",team:"SEA",pos:"RB",min:"154",max:"190",stddev:"18",tier:"7",value:"Moderate",notes:"Shoulder issue to start season.  Competing with Rashaad Penny for 2nd RB slot.",},
{rank:"211",name:"Matt Gay",team:"TB",pos:"K",min:"182",max:"216",stddev:"14.08",tier:"2",value:"",notes:"",},
{rank:"212",name:"Indianapolis Colts",team:"IND",pos:"DST",min:"162",max:"260",stddev:"41.71",tier:"2",value:"",notes:"",},
{rank:"213",name:"Chris Thompson",team:"JAC",pos:"RB",min:"176",max:"219",stddev:"17.68",tier:"5",value:"Moderate",notes:"3rd down back.",},
{rank:"214",name:"Brandon McManus",team:"DEN",pos:"K",min:"188",max:"243",stddev:"23.17",tier:"",value:"",notes:"",},
{rank:"215",name:"Ka'imi Fairbairn",team:"HOU",pos:"K",min:"192",max:"229",stddev:"14.92",tier:"3",value:"",notes:"",},
{rank:"216",name:"Mohamed Sanu",team:"NE",pos:"WR",min:"170",max:"184",stddev:"7",tier:"7",value:"",notes:"",},
{rank:"217",name:"Mason Crosby",team:"GB",pos:"K",min:"202",max:"228",stddev:"9.94",tier:"",value:"",notes:"",},
{rank:"218",name:"Tampa Bay Buccaneers",team:"TB",pos:"DST",min:"166",max:"272",stddev:"45.38",tier:"",value:"",notes:"",},
{rank:"219",name:"Nick Foles",team:"CHI",pos:"QB",min:"192",max:"240",stddev:"20.78",tier:"",value:"",notes:"",},
{rank:"220",name:"Michael Badgley",team:"LAC",pos:"K",min:"196",max:"213",stddev:"7.79",tier:"",value:"",notes:"",},
{rank:"221",name:"Giovani Bernard",team:"CIN",pos:"RB",min:"148",max:"258",stddev:"45.03",tier:"",value:"",notes:"",},
{rank:"222",name:"Bryce Love",team:"WAS",pos:"RB",min:"144",max:"219",stddev:"37.5",tier:"",value:"",notes:"",},
{rank:"223",name:"Jason Myers",team:"SEA",pos:"K",min:"176",max:"247",stddev:"26.1",tier:"",value:"",notes:"",},
{rank:"224",name:"Cleveland Browns",team:"CLE",pos:"DST",min:"188",max:"242",stddev:"20.24",tier:"3",value:"",notes:"",},
{rank:"225",name:"Jamaal Williams",team:"GB",pos:"RB",min:"175",max:"222",stddev:"20.89",tier:"",value:"",notes:"",},
{rank:"226",name:"New York Jets",team:"NYJ",pos:"DST",min:"189",max:"220",stddev:"13.42",tier:"",value:"",notes:"",},
{rank:"227",name:"Green Bay Packers",team:"GB",pos:"DST",min:"194",max:"220",stddev:"10.66",tier:"",value:"",notes:"",},
{rank:"228",name:"Gerald Everett",team:"LAR",pos:"TE",min:"195",max:"227",stddev:"13.6",tier:"",value:"",notes:"",},
{rank:"229",name:"Gus Edwards",team:"BAL",pos:"RB",min:"185",max:"193",stddev:"4",tier:"",value:"",notes:"",},
{rank:"230",name:"Dwayne Haskins",team:"WAS",pos:"QB",min:"160",max:"278",stddev:"42.44",tier:"",value:"",notes:"",},
{rank:"231",name:"Chris Boswell",team:"PIT",pos:"K",min:"182",max:"281",stddev:"36.82",tier:"2",value:"",notes:"",},
{rank:"232",name:"Denzel Mims",team:"NYJ",pos:"WR",min:"182",max:"199",stddev:"8.5",tier:"7",value:"Moderate",notes:"Rookie.  Could compete as top perimeter target in NYJ",},
{rank:"233",name:"Miles Boykin",team:"BAL",pos:"WR",min:"175",max:"236",stddev:"25.59",tier:"",value:"",notes:"",},
{rank:"234",name:"Dede Westbrook",team:"JAC",pos:"WR",min:"179",max:"203",stddev:"12",tier:"",value:"",notes:"",},
{rank:"235",name:"Malcolm Brown",team:"LAR",pos:"RB",min:"171",max:"212",stddev:"20.5",tier:"",value:"",notes:"",},
{rank:"236",name:"Benny Snell Jr.",team:"PIT",pos:"RB",min:"169",max:"253",stddev:"34.32",tier:"",value:"",notes:"",},
{rank:"237",name:"Tyrell Williams",team:"LV",pos:"WR",min:"186",max:"201",stddev:"7.5",tier:"",value:"",notes:"",},
{rank:"238",name:"Brian Hill",team:"ATL",pos:"RB",min:"141",max:"141",stddev:"0",tier:"",value:"",notes:"",},
{rank:"239",name:"Devonta Freeman",team:"FA",pos:"RB",min:"158",max:"232",stddev:"37",tier:"",value:"",notes:"",},
{rank:"240",name:"Randall Cobb",team:"HOU",pos:"WR",min:"196",max:"222",stddev:"12.03",tier:"7",value:"",notes:"",},
{rank:"241",name:"Royce Freeman",team:"DEN",pos:"RB",min:"162",max:"230",stddev:"34",tier:"",value:"",notes:"",},
{rank:"242",name:"Steven Sims",team:"WAS",pos:"WR",min:"148",max:"294",stddev:"73",tier:"",value:"",notes:"",},
{rank:"243",name:"Younghoe Koo",team:"ATL",pos:"K",min:"193",max:"293",stddev:"38.04",tier:"",value:"",notes:"",},
{rank:"244",name:"C.J. Uzomah",team:"CIN",pos:"TE",min:"185",max:"212",stddev:"13.5",tier:"",value:"",notes:"",},
{rank:"245",name:"Tyler Eifert",team:"JAC",pos:"TE",min:"167",max:"334",stddev:"68.86",tier:"",value:"",notes:"",},
{rank:"246",name:"Auden Tate",team:"CIN",pos:"WR",min:"155",max:"255",stddev:"50",tier:"",value:"",notes:"",},
{rank:"247",name:"Corey Davis",team:"TEN",pos:"WR",min:"200",max:"204",stddev:"2",tier:"",value:"",notes:"",},
{rank:"248",name:"Darrel Williams",team:"KC",pos:"RB",min:"156",max:"303",stddev:"73.5",tier:"",value:"",notes:"",},
{rank:"249",name:"Jordan Reed",team:"SF",pos:"TE",min:"157",max:"157",stddev:"0",tier:"",value:"",notes:"",},
{rank:"250",name:"Kenny Stills",team:"HOU",pos:"WR",min:"189",max:"221",stddev:"16",tier:"",value:"",notes:"",},
{rank:"251",name:"Tee Higgins",team:"CIN",pos:"WR",min:"198",max:"218",stddev:"10",tier:"7",value:"",notes:"",},
{rank:"252",name:"John Ross",team:"CIN",pos:"WR",min:"183",max:"234",stddev:"25.5",tier:"",value:"",notes:"",},
{rank:"253",name:"LeSean McCoy",team:"TB",pos:"RB",min:"177",max:"177",stddev:"0",tier:"",value:"",notes:"",},
{rank:"254",name:"Jordan Akins",team:"HOU",pos:"TE",min:"187",max:"292",stddev:"42.87",tier:"",value:"",notes:"",},
{rank:"255",name:"Logan Thomas",team:"WAS",pos:"TE",min:"181",max:"181",stddev:"0",tier:"",value:"",notes:"",},
{rank:"256",name:"Cole Beasley",team:"BUF",pos:"WR",min:"215",max:"215",stddev:"0",tier:"",value:"",notes:"",},
{rank:"257",name:"Cincinnati Bengals",team:"CIN",pos:"DST",min:"183",max:"183",stddev:"0",tier:"",value:"",notes:"",},
{rank:"258",name:"Randy Bullock",team:"CIN",pos:"K",min:"189",max:"340",stddev:"75.5",tier:"",value:"",notes:"",},
{rank:"259",name:"Darren Fells",team:"HOU",pos:"TE",min:"203",max:"298",stddev:"39.38",tier:"",value:"",notes:"",},
{rank:"260",name:"Kyle Rudolph",team:"MIN",pos:"TE",min:"192",max:"254",stddev:"31",tier:"",value:"",notes:"",},
{rank:"261",name:"Andy Isabella",team:"ARI",pos:"WR",min:"217",max:"224",stddev:"3.5",tier:"",value:"",notes:"",},
{rank:"262",name:"Joshua Kelley",team:"LAC",pos:"RB",min:"194",max:"194",stddev:"0",tier:"7",value:"Moderate",notes:"Rookie.  Competing with Justin Jackson for spot behind Austin Ekeler.",},
{rank:"263",name:"Tua Tagovailoa",team:"MIA",pos:"QB",min:"206",max:"331",stddev:"45.93",tier:"",value:"",notes:"",},
{rank:"264",name:"Detroit Lions",team:"DET",pos:"DST",min:"198",max:"316",stddev:"59",tier:"",value:"",notes:"",},
{rank:"265",name:"Dan Arnold",team:"ARI",pos:"TE",min:"200",max:"200",stddev:"0",tier:"",value:"",notes:"",},
{rank:"266",name:"Justin Herbert",team:"LAC",pos:"QB",min:"207",max:"349",stddev:"52.85",tier:"",value:"",notes:"",},
{rank:"267",name:"Jameis Winston",team:"NO",pos:"QB",min:"209",max:"353",stddev:"54.21",tier:"",value:"",notes:"",},
{rank:"268",name:"Andy Dalton",team:"DAL",pos:"QB",min:"208",max:"342",stddev:"56.87",tier:"",value:"",notes:"",},
{rank:"269",name:"Peyton Barber",team:"WAS",pos:"RB",min:"212",max:"239",stddev:"13.5",tier:"",value:"",notes:"",},
{rank:"270",name:"Marcus Mariota",team:"LV",pos:"QB",min:"213",max:"359",stddev:"63.43",tier:"",value:"",notes:"",},
{rank:"271",name:"Russell Gage",team:"ATL",pos:"WR",min:"206",max:"308",stddev:"51",tier:"",value:"",notes:"",},
{rank:"272",name:"David Njoku",team:"CLE",pos:"TE",min:"215",max:"240",stddev:"12.5",tier:"",value:"",notes:"",},
{rank:"273",name:"Joey Slye",team:"CAR",pos:"K",min:"223",max:"282",stddev:"25.95",tier:"",value:"",notes:"",},
{rank:"274",name:"Jarrett Stidham",team:"NE",pos:"QB",min:"211",max:"313",stddev:"42.5",tier:"",value:"",notes:"",},
{rank:"275",name:"Jalen Hurts",team:"PHI",pos:"QB",min:"210",max:"210",stddev:"0",tier:"",value:"",notes:"",},
{rank:"276",name:"Taysom Hill",team:"NO",pos:"QB",min:"212",max:"246",stddev:"17",tier:"",value:"",notes:"",},
{rank:"277",name:"Rashaad Penny",team:"SEA",pos:"RB",min:"213",max:"251",stddev:"19",tier:"",value:"",notes:"",},
{rank:"278",name:"Will Dissly",team:"SEA",pos:"TE",min:"217",max:"252",stddev:"17.5",tier:"",value:"",notes:"",},
{rank:"279",name:"Jimmy Graham",team:"CHI",pos:"TE",min:"231",max:"235",stddev:"2",tier:"",value:"",notes:"",},
{rank:"280",name:"Cameron Brate",team:"TB",pos:"TE",min:"221",max:"267",stddev:"23",tier:"",value:"",notes:"",},
{rank:"281",name:"Darrynton Evans",team:"TEN",pos:"RB",min:"224",max:"250",stddev:"13",tier:"7",value:"Good",notes:"Backup to Derrick Henry.",},
{rank:"282",name:"Vance McDonald",team:"PIT",pos:"TE",min:"225",max:"261",stddev:"18",tier:"",value:"",notes:"",},
{rank:"283",name:"Chris Conley",team:"JAC",pos:"WR",min:"226",max:"226",stddev:"0",tier:"",value:"",notes:"",},
{rank:"284",name:"Justice Hill",team:"BAL",pos:"RB",min:"230",max:"324",stddev:"47",tier:"",value:"",notes:"",},
{rank:"285",name:"Austin Seibert",team:"CLE",pos:"K",min:"233",max:"301",stddev:"34",tier:"3",value:"",notes:"",},
{rank:"286",name:"Kendrick Bourne",team:"SF",pos:"WR",min:"233",max:"326",stddev:"46.5",tier:"",value:"",notes:"",},
{rank:"287",name:"Tre'Quan Smith",team:"NO",pos:"WR",min:"234",max:"234",stddev:"0",tier:"",value:"",notes:"",},
{rank:"288",name:"Josh Lambo",team:"JAC",pos:"K",min:"234",max:"270",stddev:"18",tier:"",value:"",notes:"",},
{rank:"289",name:"Mitch Trubisky",team:"CHI",pos:"QB",min:"239",max:"327",stddev:"40.57",tier:"",value:"",notes:"",},
{rank:"290",name:"Houston Texans",team:"HOU",pos:"DST",min:"235",max:"296",stddev:"30.5",tier:"",value:"",notes:"",},
{rank:"291",name:"Danny Amendola",team:"DET",pos:"WR",min:"237",max:"237",stddev:"0",tier:"",value:"",notes:"",},
{rank:"292",name:"Trey Burton",team:"IND",pos:"TE",min:"237",max:"285",stddev:"24",tier:"",value:"",notes:"",},
{rank:"293",name:"Taylor Gabriel",team:"FA",pos:"WR",min:"238",max:"238",stddev:"0",tier:"",value:"",notes:"",},
{rank:"294",name:"Stephen Hauschka",team:"FA",pos:"K",min:"239",max:"286",stddev:"23.5",tier:"",value:"",notes:"",},
{rank:"295",name:"Nelson Agholor",team:"LV",pos:"WR",min:"241",max:"241",stddev:"0",tier:"",value:"",notes:"",},
{rank:"296",name:"Eddy Pineiro",team:"CHI",pos:"K",min:"242",max:"242",stddev:"0",tier:"",value:"",notes:"",},
{rank:"297",name:"Justin Rohrwasser",team:"NE",pos:"K",min:"246",max:"246",stddev:"0",tier:"",value:"",notes:"",},
{rank:"298",name:"DaeSean Hamilton",team:"DEN",pos:"WR",min:"256",max:"256",stddev:"0",tier:"",value:"",notes:"",},
{rank:"299",name:"Zach Pascal",team:"IND",pos:"WR",min:"257",max:"257",stddev:"0",tier:"",value:"",notes:"",},
{rank:"300",name:"J.J. Arcega-Whiteside",team:"PHI",pos:"WR",min:"259",max:"259",stddev:"0",tier:"",value:"",notes:"",},
{rank:"301",name:"David Moore",team:"SEA",pos:"WR",min:"262",max:"262",stddev:"0",tier:"",value:"",notes:"",},
{rank:"302",name:"Demarcus Robinson",team:"KC",pos:"WR",min:"263",max:"263",stddev:"0",tier:"",value:"",notes:"",},
{rank:"303",name:"Marquez Valdes-Scantling",team:"GB",pos:"WR",min:"264",max:"264",stddev:"0",tier:"",value:"",notes:"",},
{rank:"304",name:"Antonio Brown",team:"FA",pos:"WR",min:"265",max:"265",stddev:"0",tier:"",value:"",notes:"",},
{rank:"305",name:"Rex Burkhead",team:"NE",pos:"RB",min:"266",max:"266",stddev:"0",tier:"",value:"",notes:"",},
{rank:"306",name:"Darwin Thompson",team:"KC",pos:"RB",min:"268",max:"268",stddev:"0",tier:"",value:"",notes:"",},
{rank:"307",name:"Dion Lewis",team:"NYG",pos:"RB",min:"271",max:"271",stddev:"0",tier:"",value:"",notes:"",},
{rank:"308",name:"Washington Football Team",team:"WAS",pos:"DST",min:"273",max:"273",stddev:"0",tier:"",value:"",notes:"",},
{rank:"309",name:"Jaylen Samuels",team:"PIT",pos:"RB",min:"274",max:"274",stddev:"0",tier:"",value:"",notes:"",},
{rank:"310",name:"Stephen Gostkowski",team:"FA",pos:"K",min:"275",max:"275",stddev:"0",tier:"",value:"",notes:"",},
{rank:"311",name:"Jacob Hollister",team:"SEA",pos:"TE",min:"276",max:"276",stddev:"0",tier:"",value:"",notes:"",},
{rank:"312",name:"Adam Humphries",team:"TEN",pos:"WR",min:"279",max:"279",stddev:"0",tier:"",value:"",notes:"",},
{rank:"313",name:"Josh Gordon",team:"FA",pos:"WR",min:"280",max:"280",stddev:"0",tier:"",value:"",notes:"",},
{rank:"314",name:"Ito Smith",team:"ATL",pos:"RB",min:"283",max:"283",stddev:"0",tier:"",value:"",notes:"",},
{rank:"315",name:"Phillip Dorsett",team:"SEA",pos:"WR",min:"284",max:"284",stddev:"0",tier:"",value:"",notes:"",},
{rank:"316",name:"Delanie Walker",team:"FA",pos:"TE",min:"287",max:"287",stddev:"0",tier:"",value:"",notes:"",},
{rank:"317",name:"Willie Snead",team:"BAL",pos:"WR",min:"288",max:"288",stddev:"0",tier:"",value:"",notes:"",},
{rank:"318",name:"Jalen Richard",team:"LV",pos:"RB",min:"289",max:"289",stddev:"0",tier:"",value:"",notes:"",},
{rank:"319",name:"Keke Coutee",team:"HOU",pos:"WR",min:"290",max:"290",stddev:"0",tier:"",value:"",notes:"",},
{rank:"320",name:"Jakobi Meyers",team:"NE",pos:"WR",min:"291",max:"291",stddev:"0",tier:"",value:"",notes:"",},
{rank:"321",name:"Brett Maher",team:"NYJ",pos:"K",min:"295",max:"295",stddev:"0",tier:"",value:"",notes:"",},
{rank:"322",name:"Keelan Cole",team:"JAC",pos:"WR",min:"297",max:"297",stddev:"0",tier:"",value:"",notes:"",},
{rank:"323",name:"Demaryius Thomas",team:"FA",pos:"WR",min:"299",max:"299",stddev:"0",tier:"",value:"",notes:"",},
{rank:"324",name:"Jacksonville Jaguars",team:"JAC",pos:"DST",min:"300",max:"300",stddev:"0",tier:"",value:"",notes:"",},
{rank:"325",name:"Aldrick Rosas",team:"FA",pos:"K",min:"302",max:"302",stddev:"0",tier:"",value:"",notes:"",},
{rank:"326",name:"Josh Reynolds",team:"LAR",pos:"WR",min:"304",max:"304",stddev:"0",tier:"",value:"",notes:"",},
{rank:"327",name:"Bo Scarbrough",team:"DET",pos:"RB",min:"305",max:"305",stddev:"0",tier:"",value:"",notes:"",},
{rank:"328",name:"Lamar Miller",team:"NE",pos:"RB",min:"306",max:"306",stddev:"0",tier:"",value:"",notes:"",},
{rank:"329",name:"Atlanta Falcons",team:"ATL",pos:"DST",min:"307",max:"307",stddev:"0",tier:"",value:"",notes:"",},
{rank:"330",name:"Mike Boone",team:"MIN",pos:"RB",min:"309",max:"309",stddev:"0",tier:"",value:"",notes:"",},
{rank:"331",name:"Greg Ward",team:"PHI",pos:"WR",min:"310",max:"310",stddev:"0",tier:"",value:"",notes:"",},
{rank:"332",name:"Carolina Panthers",team:"CAR",pos:"DST",min:"311",max:"311",stddev:"0",tier:"",value:"",notes:"",},
{rank:"333",name:"Jason Witten",team:"LV",pos:"TE",min:"312",max:"312",stddev:"0",tier:"",value:"",notes:"",},
{rank:"334",name:"Patrick Laird",team:"MIA",pos:"RB",min:"314",max:"314",stddev:"0",tier:"",value:"",notes:"",},
{rank:"335",name:"Jordan Wilkins",team:"IND",pos:"RB",min:"315",max:"315",stddev:"0",tier:"",value:"",notes:"",},
{rank:"336",name:"Kai Forbath",team:"FA",pos:"K",min:"317",max:"317",stddev:"0",tier:"",value:"",notes:"",},
{rank:"337",name:"Daniel Carlson",team:"LV",pos:"K",min:"319",max:"319",stddev:"0",tier:"",value:"",notes:"",},
{rank:"338",name:"T.J. Yeldon",team:"BUF",pos:"RB",min:"320",max:"320",stddev:"0",tier:"",value:"",notes:"",},
{rank:"339",name:"Ted Ginn",team:"CHI",pos:"WR",min:"321",max:"321",stddev:"0",tier:"",value:"",notes:"",},
{rank:"340",name:"Mike Davis",team:"CAR",pos:"RB",min:"322",max:"322",stddev:"0",tier:"",value:"",notes:"",},
{rank:"341",name:"Las Vegas Raiders",team:"LV",pos:"DST",min:"323",max:"323",stddev:"0",tier:"",value:"",notes:"",},
{rank:"342",name:"Adam Vinatieri",team:"FA",pos:"K",min:"325",max:"325",stddev:"0",tier:"",value:"",notes:"",},
{rank:"343",name:"Cole Kmet",team:"CHI",pos:"TE",min:"328",max:"328",stddev:"0",tier:"",value:"",notes:"",},
{rank:"344",name:"Wayne Gallman",team:"NYG",pos:"RB",min:"329",max:"329",stddev:"0",tier:"",value:"",notes:"",},
{rank:"345",name:"Myles Gaskin",team:"MIA",pos:"RB",min:"330",max:"330",stddev:"0",tier:"",value:"",notes:"",},
{rank:"346",name:"Dustin Hopkins",team:"WAS",pos:"K",min:"332",max:"332",stddev:"0",tier:"",value:"",notes:"",},
{rank:"347",name:"Justin Watson",team:"TB",pos:"WR",min:"333",max:"333",stddev:"0",tier:"",value:"",notes:"",},
{rank:"348",name:"Chase McLaughlin",team:"IND",pos:"K",min:"335",max:"335",stddev:"0",tier:"",value:"",notes:"",},
{rank:"349",name:"Dante Pettis",team:"SF",pos:"WR",min:"336",max:"336",stddev:"0",tier:"",value:"",notes:"",},
{rank:"350",name:"Paul Richardson Jr.",team:"SEA",pos:"WR",min:"337",max:"337",stddev:"0",tier:"",value:"",notes:"",},
{rank:"351",name:"Zay Jones",team:"LV",pos:"WR",min:"338",max:"338",stddev:"0",tier:"",value:"",notes:"",},
{rank:"352",name:"KeeSean Johnson",team:"ARI",pos:"WR",min:"339",max:"339",stddev:"0",tier:"",value:"",notes:"",},
{rank:"353",name:"Dare Ogunbowale",team:"TB",pos:"RB",min:"341",max:"341",stddev:"0",tier:"",value:"",notes:"",},
{rank:"354",name:"Travis Homer",team:"SEA",pos:"RB",min:"343",max:"343",stddev:"0",tier:"",value:"",notes:"",},
{rank:"355",name:"KJ Hamler",team:"DEN",pos:"WR",min:"344",max:"344",stddev:"0",tier:"",value:"",notes:"",},
{rank:"356",name:"Reggie Bonnafon",team:"CAR",pos:"RB",min:"345",max:"345",stddev:"0",tier:"",value:"",notes:"",},
{rank:"357",name:"Qadree Ollison",team:"ATL",pos:"RB",min:"346",max:"346",stddev:"0",tier:"",value:"",notes:"",},
{rank:"358",name:"Kalen Ballage",team:"MIA",pos:"RB",min:"347",max:"347",stddev:"0",tier:"",value:"",notes:"",},
{rank:"359",name:"Ty Johnson",team:"DET",pos:"RB",min:"348",max:"348",stddev:"0",tier:"",value:"",notes:"",},
{rank:"360",name:"Ty Montgomery",team:"NO",pos:"RB",min:"350",max:"350",stddev:"0",tier:"",value:"",notes:"",},
{rank:"361",name:"Jerick McKinnon",team:"SF",pos:"RB",min:"351",max:"351",stddev:"0",tier:"6",value:"Moderate",notes:"Missed all of 2019 due to injury.",},
{rank:"362",name:"Frank Gore",team:"NYJ",pos:"RB",min:"352",max:"352",stddev:"0",tier:"",value:"",notes:"",},
{rank:"363",name:"Jeff Wilson",team:"SF",pos:"RB",min:"354",max:"354",stddev:"0",tier:"",value:"",notes:"",},
{rank:"364",name:"Jacoby Brissett",team:"IND",pos:"QB",min:"355",max:"355",stddev:"0",tier:"",value:"",notes:"",},
{rank:"365",name:"Dexter Williams",team:"GB",pos:"RB",min:"356",max:"356",stddev:"0",tier:"",value:"",notes:"",},
{rank:"366",name:"Bilal Powell",team:"FA",pos:"RB",min:"357",max:"357",stddev:"0",tier:"",value:"",notes:"",},
{rank:"367",name:"Dontrell Hilliard",team:"CLE",pos:"RB",min:"358",max:"358",stddev:"0",tier:"",value:"",notes:"",},
{rank:"368",name:"Van Jefferson",team:"LAR",pos:"WR",min:"360",max:"360",stddev:"0",tier:"",value:"",notes:"",},
]
