teamDepthCharts = [
{ team:"ARI",
  QB: ["Kyler Murray", "Colt McCoy", "Clayton Tune", "David Blough", "Jeff Driskel",  ],
  RB: ["James Conner", "Keaontay Ingram", "Corey Clement", "Ty'Son Williams",  ],
  WR: ["Marquise Brown", "Rondale Moore", "Michael Wilson", "Greg Dortch", "Zach Pascal",  ],
  TE: ["Trey McBride", "Zach Ertz", "Geoff Swaim",  ],
},
{ team:"ATL",
  QB: ["Desmond Ridder", "Taylor Heinicke", "Feleipe Franks",  ],
  RB: ["Bijan Robinson", "Tyler Allgeier", "Cordarrelle Patterson", "Avery Williams", "Keith Smith",  ],
  WR: ["Drake London", "Mack Hollins", "Scott Miller", "KhaDarel Hodge", "Josh Ali",  ],
  TE: ["Kyle Pitts", "Jonnu Smith", "Parker Hesse", "MyCole Pruitt",  ],
},
{ team:"BAL",
  QB: ["Lamar Jackson", "Tyler Huntley",  ],
  RB: ["J.K. Dobbins", "Gus Edwards", "Melvin Gordon III", "Justice Hill", "Keaton Mitchell", "Patrick Ricard",  ],
  WR: ["Rashod Bateman", "Zay Flowers", "Odell Beckham Jr.", "Devin Duvernay", "Nelson Agholor", "Tylan Wallace", "James Proche II",  ],
  TE: ["Mark Andrews", "Isaiah Likely", "Charlie Kolar",  ],
},
{ team:"BUF",
  QB: ["Josh Allen", "Kyle Allen",  ],
  RB: ["James Cook", "Damien Harris", "Latavius Murray", "Darrynton Evans", "Reggie Gilliam",  ],
  WR: ["Stefon Diggs", "Gabe Davis", "Khalil Shakir", "Deonte Harty", "Trent Sherfield", "Justin Shorter", "Dezmon Patmon",  ],
  TE: ["Dalton Kincaid", "Dawson Knox", "Quintin Morris",  ],
},
{ team:"CAR",
  QB: ["Bryce Young", "Andy Dalton", "Matt Corral",  ],
  RB: ["Miles Sanders", "Chuba Hubbard", "Raheem Blackshear",  ],
  WR: ["DJ Chark Jr.", "Adam Thielen", "Jonathan Mingo", "Terrace Marshall Jr.", "Laviska Shenault Jr.", "Shi Smith", "Damiere Byrd",  ],
  TE: ["Hayden Hurst", "Tommy Tremble", "Ian Thomas", "Giovanni Ricci", "Stephen Sullivan",  ],
},
{ team:"CHI",
  QB: ["Justin Fields", "P.J. Walker",  ],
  RB: ["Khalil Herbert", "D'Onta Foreman", "Roschon Johnson", "Travis Homer", "Trestan Ebner", "Khari Blasingame",  ],
  WR: ["DJ Moore", "Darnell Mooney", "Chase Claypool", "Tyler Scott", "Velus Jones Jr.", "Equanimeous St. Brown", "Dante Pettis",  ],
  TE: ["Cole Kmet", "Robert Tonyan", "Marcedes Lewis",  ],
},
{ team:"CIN",
  QB: ["Joe Burrow", "Trevor Siemian",  ],
  RB: ["Joe Mixon", "Chase Brown", "Chris Evans", "Trayveon Williams",  ],
  WR: ["Ja'Marr Chase", "Tee Higgins", "Tyler Boyd", "Charlie Jones", "Trenton Irwin", "Andrei Iosivas", "Trent Taylor",  ],
  TE: ["Irv Smith Jr.", "Drew Sample", "Devin Asiasi", "Tanner Hudson", "Mitchell Wilcox",  ],
},
{ team:"CLE",
  QB: ["Deshaun Watson", "Joshua Dobbs", "Dorian Thompson-Robinson",  ],
  RB: ["Nick Chubb", "Jerome Ford", "Demetric Felton Jr.", "John Kelly Jr.",  ],
  WR: ["Amari Cooper", "Elijah Moore", "Donovan Peoples-Jones", "Cedric Tillman", "David Bell", "Marquise Goodwin", "Demetric Felton Jr.", "Anthony Schwartz", "Michael Woods II",  ],
  TE: ["David Njoku", "Harrison Bryant", "Jordan Akins",  ],
},
{ team:"DAL",
  QB: ["Dak Prescott", "Cooper Rush",  ],
  RB: ["Tony Pollard", "Malik Davis", "Ronald Jones II", "Deuce Vaughn", "Rico Dowdle",  ],
  WR: ["CeeDee Lamb", "Brandin Cooks", "Michael Gallup", "Jalen Tolbert", "KaVontae Turpin", "Dennis Houston",  ],
  TE: ["Jake Ferguson", "Luke Schoonmaker", "Peyton Hendershot", "Sean McKeon",  ],
},
{ team:"DEN",
  QB: ["Russell Wilson", "Jarrett Stidham",  ],
  RB: ["Javonte Williams", "Samaje Perine", "Tyler Badie", "Tony Jones Jr.", "Jaleel McLaughlin", "Michael Burton",  ],
  WR: ["Jerry Jeudy", "Courtland Sutton", "Marvin Mims Jr.", "Tim Patrick", "Marquez Callaway", "Kendall Hinton", "Montrell Washington", "Michael Bandy",  ],
  TE: ["Greg Dulcich", "Albert Okwuegbunam", "Adam Trautman", "Chris Manhertz",  ],
},
{ team:"DET",
  QB: ["Jared Goff", "Teddy Bridgewater", "Hendon Hooker", "Nate Sudfeld",  ],
  RB: ["Jahmyr Gibbs", "David Montgomery", "Craig Reynolds", "Mohamed Ibrahim", "Jermar Jefferson",  ],
  WR: ["Amon-Ra St. Brown", "Jameson Williams", "Marvin Jones Jr.", "Josh Reynolds", "Kalif Raymond", "Denzel Mims", "Antoine Green",  ],
  TE: ["Sam LaPorta", "Brock Wright", "James Mitchell", "Shane Zylstra",  ],
},
{ team:"GB",
  QB: ["Jordan Love", "Sean Clifford",  ],
  RB: ["Aaron Jones", "AJ Dillon", "Lew Nichols III", "Patrick Taylor Jr.",  ],
  WR: ["Christian Watson", "Romeo Doubs", "Jayden Reed", "Samori Toure", "Dontayvion Wicks",  ],
  TE: ["Luke Musgrave", "Tucker Kraft", "Josiah Deguara", "Tyler Davis",  ],
},
{ team:"HOU",
  QB: ["C.J. Stroud", "Davis Mills", "Case Keenum",  ],
  RB: ["Dameon Pierce", "Devin Singletary", "Mike Boone", "Dare Ogunbowale",  ],
  WR: ["Nico Collins", "John Metchie III", "Robert Woods", "Tank Dell", "Xavier Hutchinson", "Noah Brown", "Steven Sims Jr.",  ],
  TE: ["Dalton Schultz", "Brevin Jordan", "Teagan Quitoriano", "Andrew Beck", "Mason Schreck",  ],
},
{ team:"IND",
  QB: ["Anthony Richardson", "Gardner Minshew II", "Sam Ehlinger",  ],
  RB: ["Jonathan Taylor", "Zack Moss", "Evan Hull", "Kenyan Drake", "Deon Jackson",  ],
  WR: ["Michael Pittman Jr.", "Alec Pierce", "Josh Downs", "Isaiah McKenzie", "Ashton Dulin", "Amari Rodgers", "Juwann Winfree", "Mike Strachan", "Breshad Perriman", "Malik Turner",  ],
  TE: ["Jelani Woods", "Mo Alie-Cox", "Kylen Granson", "Will Mallory", "Pharaoh Brown", "Andrew Ogletree",  ],
},
{ team:"JAC",
  QB: ["Trevor Lawrence", "C.J. Beathard",  ],
  RB: ["Travis Etienne Jr.", "Tank Bigsby", "D'Ernest Johnson", "JaMycal Hasty", "Snoop Conner",  ],
  WR: ["Calvin Ridley", "Christian Kirk", "Zay Jones", "Jamal Agnew", "Parker Washington", "Kendric Pryor", "Tim Jones",  ],
  TE: ["Evan Engram", "Brenton Strange", "Luke Farrell", "Jacob Harris",  ],
},
{ team:"KC",
  QB: ["Patrick Mahomes II", "Blaine Gabbert",  ],
  RB: ["Isiah Pacheco", "Jerick McKinnon", "Clyde Edwards-Helaire", "Deneric Prince",  ],
  WR: ["Kadarius Toney", "Skyy Moore", "Marquez Valdes-Scantling", "Rashee Rice", "Richie James Jr.", "Justyn Ross", "Justin Watson", "Ihmir Smith-Marsette",  ],
  TE: ["Travis Kelce", "Noah Gray", "Jody Fortson", "Kendall Blanton", "Blake Bell",  ],
},
{ team:"LAC",
  QB: ["Justin Herbert", "Easton Stick",  ],
  RB: ["Austin Ekeler", "Joshua Kelley", "Isaiah Spiller", "Zander Horvath",  ],
  WR: ["Keenan Allen", "Mike Williams", "Quentin Johnston", "Joshua Palmer", "Jalen Guyton", "Derius Davis",  ],
  TE: ["Gerald Everett", "Donald Parham Jr.", "Tre' McKitty", "Stone Smartt",  ],
},
{ team:"LAR",
  QB: ["Matthew Stafford", "Stetson Bennett", "Brett Rypien",  ],
  RB: ["Cam Akers", "Zach Evans", "Kyren Williams", "Royce Freeman", "Ronnie Rivers",  ],
  WR: ["Cooper Kupp", "Van Jefferson", "Puka Nacua", "Tutu Atwell", "Ben Skowronek", "Demarcus Robinson",  ],
  TE: ["Tyler Higbee", "Hunter Long", "Brycen Hopkins", "Davis Allen",  ],
},
{ team:"LV",
  QB: ["Jimmy Garoppolo", "Brian Hoyer", "Aidan O'Connell",  ],
  RB: ["Josh Jacobs", "Zamir White", "Ameer Abdullah", "Brandon Bolden", "Damien Williams", "Brittain Brown", "Jakob Johnson",  ],
  WR: ["Davante Adams", "Jakobi Meyers", "Hunter Renfrow", "DeAndre Carter", "Tre Tucker", "Cam Sims", "Phillip Dorsett II", "Keelan Cole Sr.", "DJ Turner",  ],
  TE: ["Michael Mayer", "Austin Hooper", "Jesper Horsted", "Jacob Hollister",  ],
},
{ team:"MIA",
  QB: ["Tua Tagovailoa", "Mike White", "Skylar Thompson",  ],
  RB: ["De'Von Achane", "Jeff Wilson Jr.", "Raheem Mostert", "Myles Gaskin", "Salvon Ahmed", "Alec Ingold",  ],
  WR: ["Tyreek Hill", "Jaylen Waddle", "Braxton Berrios", "Robbie Chosen", "Cedrick Wilson Jr.", "Erik Ezukanma", "River Cracraft", "Tanner Conner",  ],
  TE: ["Durham Smythe", "Elijah Higgins", "Eric Saubert",  ],
},
{ team:"MIN",
  QB: ["Kirk Cousins", "Nick Mullens", "Jaren Hall",  ],
  RB: ["Alexander Mattison", "DeWayne McBride", "Ty Chandler", "Kene Nwangwu", "C.J. Ham",  ],
  WR: ["Justin Jefferson", "Jordan Addison", "K.J. Osborn", "Jalen Nailor", "Brandon Powell", "Jalen Reagor", "N'Keal Harry", "Blake Proehl",  ],
  TE: ["T.J. Hockenson", "Josh Oliver", "Johnny Mundt",  ],
},
{ team:"NE",
  QB: ["Mac Jones", "Bailey Zappe", "Malik Cunningham",  ],
  RB: ["Rhamondre Stevenson", "Ezekiel Elliott", "Pierre Strong Jr.", "Kevin Harris", "Ty Montgomery", "J.J. Taylor",  ],
  WR: ["JuJu Smith-Schuster", "DeVante Parker", "Tyquan Thornton", "Kendrick Bourne", "Kayshon Boutte", "Demario Douglas", "Matthew Slater",  ],
  TE: ["Hunter Henry", "Mike Gesicki",  ],
},
{ team:"NO",
  QB: ["Derek Carr", "Jameis Winston", "Jake Haener",  ],
  RB: ["Alvin Kamara", "Jamaal Williams", "Kendre Miller", "Darrel Williams", "Adam Prentice",  ],
  WR: ["Chris Olave", "Michael Thomas", "Rashid Shaheed", "A.T. Perry", "Tre'Quan Smith", "Bryan Edwards",  ],
  TE: ["Juwan Johnson", "Taysom Hill", "Foster Moreau", "Jimmy Graham",  ],
},
{ team:"NYG",
  QB: ["Daniel Jones", "Tyrod Taylor",  ],
  RB: ["Saquon Barkley", "Matt Breida", "James Robinson", "Eric Gray", "Gary Brightwell",  ],
  WR: ["Isaiah Hodgins", "Darius Slayton", "Wan'Dale Robinson", "Parris Campbell", "Jalin Hyatt", "Sterling Shepard", "Jamison Crowder", "Bryce Ford-Wheaton", "David Sills V", "Collin Johnson", "Cole Beasley",  ],
  TE: ["Darren Waller", "Daniel Bellinger", "Tommy Sweeney", "Chris Myarick",  ],
},
{ team:"NYJ",
  QB: ["Aaron Rodgers", "Zach Wilson", "Tim Boyle",  ],
  RB: ["Breece Hall", "Dalvin Cook", "Michael Carter", "Israel Abanikanda", "Zonovan Knight", "Nick Bawden",  ],
  WR: ["Garrett Wilson", "Allen Lazard", "Mecole Hardman Jr.", "Corey Davis", "Randall Cobb", "Jason Brownlee",  ],
  TE: ["Tyler Conklin", "C.J. Uzomah", "Jeremy Ruckert", "Zack Kuntz", "Kenny Yeboah",  ],
},
{ team:"PHI",
  QB: ["Jalen Hurts", "Marcus Mariota", "Tanner McKee",  ],
  RB: ["D'Andre Swift", "Rashaad Penny", "Kenneth Gainwell", "Boston Scott", "Trey Sermon",  ],
  WR: ["A.J. Brown", "DeVonta Smith", "Quez Watkins", "Olamide Zaccheaus", "Tyrie Cleveland", "Britain Covey",  ],
  TE: ["Dallas Goedert", "Dan Arnold", "Grant Calcaterra", "Jack Stoll", "Tyree Jackson",  ],
},
{ team:"PIT",
  QB: ["Kenny Pickett", "Mitch Trubisky", "Mason Rudolph",  ],
  RB: ["Najee Harris", "Jaylen Warren", "Anthony McFarland Jr.",  ],
  WR: ["Diontae Johnson", "George Pickens", "Allen Robinson II", "Calvin Austin III", "Miles Boykin", "Gunner Olszewski", "Dez Fitzpatrick",  ],
  TE: ["Pat Freiermuth", "Darnell Washington", "Connor Heyward", "Zach Gentry",  ],
},
{ team:"SEA",
  QB: ["Geno Smith", "Drew Lock",  ],
  RB: ["Kenneth Walker III", "Zach Charbonnet", "DeeJay Dallas", "Kenny McIntosh",  ],
  WR: ["DK Metcalf", "Tyler Lockett", "Jaxon Smith-Njigba", "Dee Eskridge", "Dareke Young",  ],
  TE: ["Noah Fant", "Will Dissly", "Colby Parkinson",  ],
},
{ team:"SF",
  QB: ["Brock Purdy", "Trey Lance", "Sam Darnold",  ],
  RB: ["Christian McCaffrey", "Elijah Mitchell", "Jordan Mason", "Tyrion Davis-Price", "Kyle Juszczyk",  ],
  WR: ["Deebo Samuel", "Brandon Aiyuk", "Jauan Jennings", "Danny Gray", "Ray-Ray McCloud III", "Ronnie Bell",  ],
  TE: ["George Kittle", "Ross Dwelley", "Cameron Latu", "Brayden Willis", "Charlie Woerner",  ],
},
{ team:"TB",
  QB: ["Baker Mayfield", "Kyle Trask", "John Wolford",  ],
  RB: ["Rachaad White", "Chase Edmonds", "Sean Tucker", "Ke'Shawn Vaughn",  ],
  WR: ["Mike Evans", "Chris Godwin", "Russell Gage", "Trey Palmer", "Deven Thompkins", "Rakim Jarrett", "Kaylon Geiger Sr.",  ],
  TE: ["Cade Otton", "Payne Durham", "Ko Kieft",  ],
},
{ team:"TEN",
  QB: ["Ryan Tannehill", "Will Levis", "Malik Willis",  ],
  RB: ["Derrick Henry", "Tyjae Spears", "Hassan Haskins", "Julius Chestnut", "Jonathan Ward",  ],
  WR: ["DeAndre Hopkins", "Treylon Burks", "Nick Westbrook-Ikhine", "Kyle Philips", "Chris Moore", "Racey McMath", "Mason Kinsey",  ],
  TE: ["Chigoziem Okonkwo", "Josh Whyle", "Kevin Rader", "Trevon Wesco",  ],
},
{ team:"WAS",
  QB: ["Sam Howell", "Jacoby Brissett", "Jake Fromm",  ],
  RB: ["Brian Robinson Jr.", "Antonio Gibson", "Chris Rodriguez Jr.", "Jonathan Williams", "Jaret Patterson",  ],
  WR: ["Terry McLaurin", "Jahan Dotson", "Curtis Samuel", "Dyami Brown", "Byron Pringle", "Dax Milne", "Marcus Kemp",  ],
  TE: ["Logan Thomas", "Cole Turner", "John Bates", "Armani Rogers",  ],
},
]
