teamDepthCharts = [
{ team:"ARI",
  QB: ["Kyler Murray", "Colt McCoy", "Chris Streveler",  ],
  RB: ["Chase Edmonds", "James Conner", "Eno Benjamin", "Jonathan Ward", "Tavien Feaster",  ],
  WR: ["DeAndre Hopkins", "Rondale Moore", "Christian Kirk", "A.J. Green", "Andy Isabella", "KeeSean Johnson",  ],
  TE: ["Maxx Williams", "Darrell Daniels", "Demetrius Harris", "Ross Travis",  ],
},
{ team:"ATL",
  QB: ["Matt Ryan", "Feleipe Franks", "Josh Rosen",  ],
  RB: ["Mike Davis", "Qadree Ollison", "D'Onta Foreman", "Keith Smith", "Caleb Huntley",  ],
  WR: ["Calvin Ridley", "Russell Gage", "Olamide Zaccheaus", "Cordarrelle Patterson", "Frank Darby", "Christian Blake", "Tajae Sharpe", "Chris Rowland", "Austin Trammell", "Juwan Green",  ],
  TE: ["Kyle Pitts", "Hayden Hurst", "Lee Smith", "Jaeden Graham", "Ryan Becker", "John Raine",  ],
},
{ team:"BAL",
  QB: ["Lamar Jackson", "Trace McSorley", "Tyler Huntley",  ],
  RB: ["Gus Edwards", "J.K. Dobbins", "Justice Hill", "Patrick Ricard", "Ty'Son Williams", "Ben Mason", "Nate McCrary",  ],
  WR: ["Marquise Brown", "Rashod Bateman", "Sammy Watkins", "Miles Boykin", "Tylan Wallace", "Devin Duvernay", "James Proche",  ],
  TE: ["Mark Andrews", "Nick Boyle", "Josh Oliver", "Eric Tomlinson", "Eli Wolf", "Jake Breeland", "Tony Poljan",  ],
},
{ team:"BUF",
  QB: ["Josh Allen", "Mitchell Trubisky", "Jake Fromm", "Davis Webb",  ],
  RB: ["Zack Moss", "Devin Singletary", "Matt Breida", "Antonio Williams", "Reggie Gilliam", "Taiwan Jones", "Kerrith Whyte Jr.",  ],
  WR: ["Stefon Diggs", "Cole Beasley", "Gabriel Davis", "Emmanuel Sanders", "Steven Sims Jr.", "Isaiah McKenzie", "Kenny Stills", "Marquez Stevenson", "Jake Kumerow", "Isaiah Hodgins", "Brandon Powell", "Duke Williams", "Tanner Gentry",  ],
  TE: ["Dawson Knox", "Jacob Hollister", "Tommy Sweeney", "Nate Becker",  ],
},
{ team:"CAR",
  QB: ["Sam Darnold", "Phillip Walker", "Will Grier",  ],
  RB: ["Christian McCaffrey", "Chuba Hubbard", "Trenton Cannon", "Reggie Bonnafon", "Rodney Smith", "Spencer Brown",  ],
  WR: ["D.J. Moore", "Robby Anderson", "Terrace Marshall Jr.", "David Moore", "Shi Smith", "Omar Bayless", "Brandon Zylstra",  ],
  TE: ["Dan Arnold", "Ian Thomas", "Tommy Tremble", "Stephen Sullivan", "Giovanni Ricci",  ],
},
{ team:"CHI",
  QB: ["Justin Fields", "Andy Dalton", "Nick Foles",  ],
  RB: ["David Montgomery", "Tarik Cohen", "Damien Williams", "Khalil Herbert", "Ryan Nall",  ],
  WR: ["Allen Robinson II", "Darnell Mooney", "Damiere Byrd", "Dazz Newsome", "Marquise Goodwin", "Isaiah Coulter", "Riley Ridley", "Rodney Adams", "Chris Lacy",  ],
  TE: ["Cole Kmet", "Jimmy Graham", "J.P. Holtz", "Jesse James", "Jesper Horsted", "Scooter Harrington",  ],
},
{ team:"CIN",
  QB: ["Joe Burrow", "Brandon Allen",  ],
  RB: ["Joe Mixon", "Samaje Perine", "Chris Evans", "Trayveon Williams", "Pooka Williams Jr.", "Jacques Patrick",  ],
  WR: ["Tee Higgins", "Ja'Marr Chase", "Tyler Boyd", "Auden Tate", "Mike Thomas", "Trent Taylor", "Trenton Irwin", "Stanley Morgan Jr.",  ],
  TE: ["C.J. Uzomah", "Drew Sample", "Thaddeus Moss", "Mason Schreck", "Mitchell Wilcox",  ],
},
{ team:"CLE",
  QB: ["Baker Mayfield", "Case Keenum", "Kyle Lauletta",  ],
  RB: ["Nick Chubb", "Kareem Hunt", "D'Ernest Johnson", "Andy Janovich", "Johnny Stanton", "John Kelly", "Tre Harbison",  ],
  WR: ["Odell Beckham Jr.", "Jarvis Landry", "Rashard Higgins", "Donovan Peoples-Jones", "Anthony Schwartz", "Demetric Felton", "KhaDarel Hodge",  ],
  TE: ["Austin Hooper", "Harrison Bryant", "David Njoku", "Stephen Carlson", "Jordan Franks",  ],
},
{ team:"DAL",
  QB: ["Dak Prescott", "Garrett Gilbert", "Cooper Rush", "Ben DiNucci",  ],
  RB: ["Ezekiel Elliott", "Tony Pollard", "Rico Dowdle", "Brenden Knox", "Sewo Olonilua", "JaQuan Hardy",  ],
  WR: ["CeeDee Lamb", "Amari Cooper", "Michael Gallup", "Cedrick Wilson", "Simi Fehoko", "Noah Brown", "Malik Turner", "Brandon Smith", "Aaron Parker", "Johnnie Dixon",  ],
  TE: ["Blake Jarwin", "Dalton Schultz", "Jeremy Sprinkle", "Sean McKeon",  ],
},
{ team:"DEN",
  QB: ["Teddy Bridgewater", "Drew Lock", "Brett Rypien",  ],
  RB: ["Javonte Williams", "Melvin Gordon III", "Mike Boone", "Royce Freeman", "Stevie Scott III", "Damarea Crockett",  ],
  WR: ["Jerry Jeudy", "Courtland Sutton", "KJ Hamler", "Tim Patrick", "Seth Williams", "DaeSean Hamilton", "Diontae Spencer", "Kendall Hinton", "Tyrie Cleveland", "Trinity Benson",  ],
  TE: ["Noah Fant", "Albert Okwuegbunam", "Eric Saubert", "Austin Fort", "Andrew Beck", "Shaun Beyer",  ],
},
{ team:"DET",
  QB: ["Jared Goff", "Tim Boyle", "David Blough",  ],
  RB: ["D'Andre Swift", "Jamaal Williams", "Jermar Jefferson", "Dedrick Mills", "Craig Reynolds",  ],
  WR: ["Breshad Perriman", "Amon-Ra St. Brown", "Tyrell Williams", "Quintez Cephus", "Kalif Raymond", "Sage Surratt", "Geronimo Allison", "Chad Hansen", "Victor Bolden Jr.", "Damion Ratley",  ],
  TE: ["T.J. Hockenson", "Darren Fells", "Hunter Bryant", "Alize Mack", "Brock Wright",  ],
},
{ team:"GB",
  QB: ["Aaron Rodgers", "Jordan Love", "Blake Bortles", "Kurt Benkert",  ],
  RB: ["Aaron Jones", "AJ Dillon", "Kylin Hill", "Dexter Williams", "Patrick Taylor Jr.",  ],
  WR: ["Davante Adams", "Allen Lazard", "Marquez Valdes-Scantling", "Randall Cobb", "Amari Rodgers", "Equanimeous St. Brown", "Malik Taylor",  ],
  TE: ["Robert Tonyan", "Jace Sternberger", "Marcedes Lewis", "Josiah Deguara", "Dominique Dafney",  ],
},
{ team:"HOU",
  QB: ["Deshaun Watson", "Tyrod Taylor", "Davis Mills", "Jeff Driskel",  ],
  RB: ["David Johnson", "Phillip Lindsay", "Mark Ingram II", "Rex Burkhead", "Dontrell Hilliard", "Buddy Howell", "Scottie Phillips",  ],
  WR: ["Brandin Cooks", "Nico Collins", "Anthony Miller", "Keke Coutee", "Chris Conley", "Andre Roberts", "Alex Erickson", "Chris Moore",  ],
  TE: ["Jordan Akins", "Brevin Jordan", "Pharaoh Brown", "Ryan Izzo", "Antony Auclair",  ],
},
{ team:"IND",
  QB: ["Carson Wentz", "Jacob Eason", "Sam Ehlinger", "Brett Hundley",  ],
  RB: ["Jonathan Taylor", "Nyheim Hines", "Marlon Mack", "Jordan Wilkins", "Deon Jackson",  ],
  WR: ["Michael Pittman Jr.", "T.Y. Hilton", "Parris Campbell", "Zach Pascal", "Mike Strachan", "Ashton Dulin", "J.J. Nelson", "Dezmon Patmon", "DeMichael Harris", "Tyler Vaughns",  ],
  TE: ["Jack Doyle", "Mo Alie-Cox", "Kylen Granson", "Jordan Thomas", "Farrod Green", "Noah Togiai", "Andrew Vollert",  ],
},
{ team:"JAC",
  QB: ["Trevor Lawrence", "C.J. Beathard", "Jake Luton",  ],
  RB: ["James Robinson", "Carlos Hyde", "Dare Ogunbowale", "Devine Ozigbo", "Nathan Cottrell",  ],
  WR: ["D.J. Chark Jr.", "Laviska Shenault Jr.", "Marvin Jones Jr.", "Collin Johnson", "Phillip Dorsett II", "Jamal Agnew", "Jalen Camp", "Pharoh Cooper", "Terry Godwin", "Laquon Treadwell", "Devin Smith", "Tavon Austin",  ],
  TE: ["James O'Shaughnessy", "Tim Tebow", "Chris Manhertz", "Luke Farrell", "Tyler Davis", "Ben Ellefson",  ],
},
{ team:"KC",
  QB: ["Patrick Mahomes II", "Chad Henne", "Shane Buechele",  ],
  RB: ["Clyde Edwards-Helaire", "Darrel Williams", "Jerick McKinnon", "Darwin Thompson", "Michael Burton",  ],
  WR: ["Tyreek Hill", "Mecole Hardman", "Byron Pringle", "Demarcus Robinson", "Cornell Powell", "Marcus Kemp", "Daurice Fountain", "Chris Finke", "Maurice Ffrench", "Dalton Schoen",  ],
  TE: ["Travis Kelce", "Noah Gray", "Blake Bell", "Nick Keizer",  ],
},
{ team:"LAC",
  QB: ["Justin Herbert", "Chase Daniel", "Easton Stick",  ],
  RB: ["Austin Ekeler", "Justin Jackson", "Joshua Kelley", "Larry Rountree III", "Darius Bradwell", "Gabe Nabers",  ],
  WR: ["Keenan Allen", "Mike Williams", "Tyron Johnson", "Josh Palmer", "Jalen Guyton", "K.J. Hill Jr.", "Joe Reed", "John Hurst", "Jason Moore",  ],
  TE: ["Jared Cook", "Donald Parham Jr.", "Tre' McKitty", "Stephen Anderson", "Matt Sokol", "Hunter Kampmoyer",  ],
},
{ team:"LAR",
  QB: ["Matthew Stafford", "John Wolford", "Bryce Perkins",  ],
  RB: ["Darrell Henderson", "Sony Michel", "Xavier Jones", "Jake Funk", "Raymond Calais", "Otis Anderson Jr.",  ],
  WR: ["Robert Woods", "Cooper Kupp", "Van Jefferson", "DeSean Jackson", "Tutu Atwell", "Ben Skowronek", "Trishton Jackson", "Jeremiah Haydel",  ],
  TE: ["Tyler Higbee", "Jacob Harris", "Brycen Hopkins", "Johnny Mundt", "Kendall Blanton",  ],
},
{ team:"LV",
  QB: ["Derek Carr", "Marcus Mariota", "Nathan Peterman",  ],
  RB: ["Josh Jacobs", "Kenyan Drake", "Jalen Richard", "Trey Ragas", "Alec Ingold", "Theo Riddick", "B.J. Emmons", "Bo Scarbrough",  ],
  WR: ["Henry Ruggs III", "John Brown", "Bryan Edwards", "Hunter Renfrow", "Willie Snead IV", "Zay Jones",  ],
  TE: ["Darren Waller", "Foster Moreau", "Derek Carrier", "Nick Bowers", "Alex Ellis", "Matt Bushman",  ],
},
{ team:"MIA",
  QB: ["Tua Tagovailoa", "Jacoby Brissett", "Reid Sinnett",  ],
  RB: ["Myles Gaskin", "Salvon Ahmed", "Malcolm Brown", "Gerrid Doaks", "Patrick Laird", "Jordan Scarlett",  ],
  WR: ["Will Fuller V", "Jaylen Waddle", "DeVante Parker", "Preston Williams", "Albert Wilson", "Jakeem Grant Sr.", "Isaiah Ford", "Mack Hollins", "Kirk Merritt", "Allen Hurns",  ],
  TE: ["Mike Gesicki", "Hunter Long", "Adam Shaheen", "Durham Smythe", "Cethan Carter",  ],
},
{ team:"MIN",
  QB: ["Kirk Cousins", "Kellen Mond", "Danny Etling", "Jake Browning", "Nate Stanley",  ],
  RB: ["Dalvin Cook", "Alexander Mattison", "Kene Nwangwu", "Ameer Abdullah", "C.J. Ham", "A.J. Rose Jr.",  ],
  WR: ["Justin Jefferson", "Adam Thielen", "Dede Westbrook", "Ihmir Smith-Marsette", "Chad Beebe", "K.J. Osborn", "Whop Philyor", "Warren Jackson",  ],
  TE: ["Irv Smith Jr.", "Tyler Conklin", "Zach Davidson", "Brandon Dillon", "Shane Zylstra",  ],
},
{ team:"NE",
  QB: ["Cam Newton", "Mac Jones", "Jarrett Stidham", "Brian Hoyer",  ],
  RB: ["Damien Harris", "James White", "Rhamondre Stevenson", "J.J. Taylor", "Brandon Bolden", "Jakob Johnson",  ],
  WR: ["Jakobi Meyers", "Nelson Agholor", "Kendrick Bourne", "N'Keal Harry", "Gunner Olszewski", "Kristian Wilkerson", "Isaiah Zuber", "Tre Nixon",  ],
  TE: ["Jonnu Smith", "Hunter Henry", "Devin Asiasi", "Dalton Keene", "Troy Fumagalli", "Matt LaCosse",  ],
},
{ team:"NO",
  QB: ["Jameis Winston", "Taysom Hill", "Ian Book", "Trevor Siemian",  ],
  RB: ["Alvin Kamara", "Latavius Murray", "Tony Jones Jr.", "Devonta Freeman", "Ty Montgomery", "Alex Armah", "Dwayne Washington",  ],
  WR: ["Michael Thomas", "Tre'Quan Smith", "Marquez Callaway", "Deonte Harris", "Lil'Jordan Humphrey", "Chris Hogan", "Juwan Johnson", "Kawaan Baker", "Kevin White", "Easop Winston Jr.",  ],
  TE: ["Adam Trautman", "Juwan Johnson", "Nick Vannett", "Garrett Griffin",  ],
},
{ team:"NYG",
  QB: ["Daniel Jones", "Mike Glennon", "Clayton Thorson",  ],
  RB: ["Saquon Barkley", "Devontae Booker", "Corey Clement", "Gary Brightwell", "Alfred Morris", "Elijhaa Penny", "Sandro Platzgummer", "Cullen Gillaspia",  ],
  WR: ["Kenny Golladay", "Sterling Shepard", "Darius Slayton", "Kadarius Toney", "John Ross", "Dante Pettis", "C.J. Board", "Rysen John", "Austin Mack",  ],
  TE: ["Evan Engram", "Kyle Rudolph", "Kaden Smith", "Cole Hikutini", "Nakia Griffin-Stewart",  ],
},
{ team:"NYJ",
  QB: ["Zach Wilson", "James Morgan", "Mike White",  ],
  RB: ["Michael Carter", "Tevin Coleman", "Ty Johnson", "La'Mical Perine", "Josh Adams",  ],
  WR: ["Corey Davis", "Elijah Moore", "Jamison Crowder", "Denzel Mims", "Keelan Cole Sr.", "Braxton Berrios", "Jeff Smith", "Lawrence Cager",  ],
  TE: ["Chris Herndon IV", "Tyler Kroft", "Ryan Griffin", "Kenny Yeboah", "Trevon Wesco", "Daniel Brown",  ],
},
{ team:"PHI",
  QB: ["Jalen Hurts", "Gardner Minshew II", "Joe Flacco",  ],
  RB: ["Miles Sanders", "Kenneth Gainwell", "Boston Scott", "Jordan Howard", "Jason Huntley",  ],
  WR: ["DeVonta Smith", "Jalen Reagor", "Travis Fulgham", "Greg Ward", "Quez Watkins", "J.J. Arcega-Whiteside", "John Hightower", "Hakeem Butler",  ],
  TE: ["Dallas Goedert", "Zach Ertz", "Richard Rodgers", "Jason Croom", "Jack Stoll",  ],
},
{ team:"PIT",
  QB: ["Ben Roethlisberger", "Dwayne Haskins", "Mason Rudolph", "Joshua Dobbs",  ],
  RB: ["Najee Harris", "Benny Snell Jr.", "Anthony McFarland Jr.", "Kalen Ballage", "Jaylen Samuels", "Derek Watt", "Tony Brooks-James", "Trey Edmunds",  ],
  WR: ["Diontae Johnson", "Chase Claypool", "JuJu Smith-Schuster", "James Washington", "Ray-Ray McCloud", "Tyler Simmons", "Cody White", "Rico Bussey",  ],
  TE: ["Eric Ebron", "Pat Freiermuth", "Zach Gentry", "Kevin Rader",  ],
},
{ team:"SEA",
  QB: ["Russell Wilson", "Geno Smith", "Sean Mannion",  ],
  RB: ["Chris Carson", "Rashaad Penny", "DeeJay Dallas", "Travis Homer", "Alex Collins",  ],
  WR: ["D.K. Metcalf", "Tyler Lockett", "D'Wayne Eskridge", "Freddie Swain", "Cade Johnson", "Penny Hart", "Aaron Fuller", "Connor Wedington", "John Ursua", "Cody Thompson",  ],
  TE: ["Gerald Everett", "Will Dissly", "Colby Parkinson", "Ian Bunting", "Tyler Mabry",  ],
},
{ team:"SF",
  QB: ["Trey Lance", "Jimmy Garoppolo", "Nate Sudfeld",  ],
  RB: ["Raheem Mostert", "Trey Sermon", "Wayne Gallman", "Jeff Wilson Jr.", "Elijah Mitchell", "Kyle Juszczyk", "JaMycal Hasty",  ],
  WR: ["Brandon Aiyuk", "Deebo Samuel", "Jalen Hurd", "Mohamed Sanu", "Trent Sherfield", "Jauan Jennings", "River Cracraft", "Travis Benjamin", "Nsimba Webster",  ],
  TE: ["George Kittle", "Ross Dwelley", "MyCole Pruitt", "Charlie Woerner",  ],
},
{ team:"TB",
  QB: ["Tom Brady", "Kyle Trask", "Blaine Gabbert", "Drew Stanton", "Ryan Griffin",  ],
  RB: ["Ronald Jones II", "Leonard Fournette", "Giovani Bernard", "Ke'Shawn Vaughn", "Troymaine Pope", "C.J. Prosise",  ],
  WR: ["Mike Evans", "Chris Godwin", "Antonio Brown", "Scotty Miller", "Tyler Johnson", "Jaelon Darden", "Justin Watson", "Jaydon Mickens",  ],
  TE: ["Rob Gronkowski", "O.J. Howard", "Cameron Brate", "Tanner Hudson", "Jerell Adams",  ],
},
{ team:"TEN",
  QB: ["Ryan Tannehill", "Logan Woodside", "Matt Barkley",  ],
  RB: ["Derrick Henry", "Darrynton Evans", "Brian Hill", "Javian Hawkins", "Jeremy McNichols", "Khari Blasingame", "Mekhi Sargent",  ],
  WR: ["A.J. Brown", "Julio Jones", "Josh Reynolds", "Dez Fitzpatrick", "Cameron Batson", "Marcus Johnson", "Chester Rogers", "Racey McMath", "Nick Westbrook-Ikhine",  ],
  TE: ["Anthony Firkser", "Geoff Swaim", "Jared Pinkney", "Tommy Hudson", "Luke Stocker",  ],
},
{ team:"WAS",
  QB: ["Ryan Fitzpatrick", "Taylor Heinicke", "Kyle Allen", "Steven Montez",  ],
  RB: ["Antonio Gibson", "J.D. McKissic", "Peyton Barber", "Jaret Patterson", "Lamar Miller", "Jonathan Williams",  ],
  WR: ["Terry McLaurin", "Curtis Samuel", "Dyami Brown", "Adam Humphries", "Antonio Gandy-Golden", "Cam Sims", "Kelvin Harmon", "Dax Milne",  ],
  TE: ["Logan Thomas", "John Bates", "Ricky Seals-Jones", "Sammis Reyes", "Caleb Wilson", "Tyrone Swoopes",  ],
},
]
