teamDepthCharts = [
{ team:"ARI",
  QB: ["Kyler Murray", "Colt McCoy", "Trace McSorley", "Jarrett Guarantano",  ],
  RB: ["James Conner", "Darrel Williams", "Eno Benjamin", "Keaontay Ingram", "Jonathan Ward",  ],
  WR: ["Marquise Brown", "DeAndre Hopkins", "Rondale Moore", "A.J. Green", "Antoine Wesley", "Andy Isabella", "Greg Dortch", "Jontre Kirklin", "JaVonta Payton",  ],
  TE: ["Zach Ertz", "Trey McBride", "Maxx Williams", "Stephen Anderson", "Chris Pierce Jr.", "Bernhard Seikovits",  ],
},
{ team:"ATL",
  QB: ["Marcus Mariota", "Desmond Ridder", "Feleipe Franks",  ],
  RB: ["Cordarrelle Patterson", "Tyler Allgeier", "Damien Williams", "Qadree Ollison", "Keith Smith", "Caleb Huntley",  ],
  WR: ["Drake London", "Bryan Edwards", "Olamide Zaccheaus", "Damiere Byrd", "KhaDarel Hodge", "Cameron Batson", "KeeSean Johnson", "Frank Darby", "Jared Bernhardt",  ],
  TE: ["Kyle Pitts", "Anthony Firkser", "Parker Hesse", "MyCole Pruitt", "John FitzPatrick",  ],
},
{ team:"BAL",
  QB: ["Lamar Jackson", "Tyler Huntley", "Anthony Brown",  ],
  RB: ["J.K. Dobbins", "Gus Edwards", "Mike Davis", "Tyler Badie", "Justice Hill", "Patrick Ricard", "Ben Mason", "Nate McCrary",  ],
  WR: ["Rashod Bateman", "Devin Duvernay", "James Proche II", "Demarcus Robinson", "Tylan Wallace", "Makai Polk", "Binjimen Victor", "Slade Bolden",  ],
  TE: ["Mark Andrews", "Isaiah Likely", "Charlie Kolar", "Nick Boyle", "Josh Oliver",  ],
},
{ team:"BUF",
  QB: ["Josh Allen", "Case Keenum", "Matt Barkley",  ],
  RB: ["Devin Singletary", "James Cook", "Zack Moss", "Duke Johnson Jr.", "Reggie Gilliam", "Taiwan Jones", "Raheem Blackshear",  ],
  WR: ["Stefon Diggs", "Gabriel Davis", "Jamison Crowder", "Isaiah McKenzie", "Khalil Shakir", "Jake Kumerow", "Isaiah Hodgins", "Tanner Gentry", "Marquez Stevenson", "Neil Pau'u",  ],
  TE: ["Dawson Knox", "O.J. Howard", "Tommy Sweeney",  ],
},
{ team:"CAR",
  QB: ["Baker Mayfield", "Sam Darnold", "PJ Walker",  ],
  RB: ["Christian McCaffrey", "D'Onta Foreman", "Chuba Hubbard", "John Lovett", "Spencer Brown",  ],
  WR: ["DJ Moore", "Robbie Anderson", "Terrace Marshall Jr.", "Rashard Higgins", "Shi Smith", "Brandon Zylstra", "Andre Roberts", "Charleston Rambo",  ],
  TE: ["Tommy Tremble", "Ian Thomas", "Stephen Sullivan", "Giovanni Ricci", "Colin Thompson", "Josh Babicz",  ],
},
{ team:"CHI",
  QB: ["Justin Fields", "Trevor Siemian", "Nathan Peterman",  ],
  RB: ["David Montgomery", "Khalil Herbert", "Darrynton Evans", "Trestan Ebner", "Khari Blasingame", "De'Montre Tuggle",  ],
  WR: ["Darnell Mooney", "Byron Pringle", "Velus Jones Jr.", "Equanimeous St. Brown", "N'Keal Harry", "Tajae Sharpe", "Dante Pettis", "Isaiah Coulter", "Nsimba Webster", "Kevin Shaa",  ],
  TE: ["Cole Kmet", "James O'Shaughnessy", "Ryan Griffin", "Chase Allen",  ],
},
{ team:"CIN",
  QB: ["Joe Burrow", "Brandon Allen", "Jake Browning",  ],
  RB: ["Joe Mixon", "Samaje Perine", "Chris Evans", "Trayveon Williams", "Jacques Patrick", "Elijah Holyfield",  ],
  WR: ["Ja'Marr Chase", "Tee Higgins", "Tyler Boyd", "Mike Thomas", "Stanley Morgan Jr.", "Trent Taylor", "Trenton Irwin", "Kwamie Lassiter II",  ],
  TE: ["Hayden Hurst", "Drew Sample", "Mitchell Wilcox", "Thaddeus Moss",  ],
},
{ team:"CLE",
  QB: ["Deshaun Watson", "Jacoby Brissett", "Joshua Dobbs", "Josh Rosen",  ],
  RB: ["Nick Chubb", "Kareem Hunt", "D'Ernest Johnson", "Jerome Ford", "Demetric Felton Jr.", "John Kelly Jr.", "Johnny Stanton IV",  ],
  WR: ["Amari Cooper", "Donovan Peoples-Jones", "David Bell", "Anthony Schwartz", "Ja'Marcus Bradley", "Javon Wims",  ],
  TE: ["David Njoku", "Harrison Bryant", "Miller Forristall", "Nakia Griffin-Stewart", "Zaire Mitchell-Paden",  ],
},
{ team:"DAL",
  QB: ["Dak Prescott", "Cooper Rush", "Will Grier", "Ben DiNucci",  ],
  RB: ["Ezekiel Elliott", "Tony Pollard", "Rico Dowdle", "Aaron Shampklin", "Malik Davis",  ],
  WR: ["CeeDee Lamb", "Michael Gallup", "Jalen Tolbert", "James Washington", "Noah Brown", "Simi Fehoko", "Dennis Houston", "KaVontae Turpin", "Dontario Drummond", "T.J. Vasher",  ],
  TE: ["Dalton Schultz", "Jake Ferguson", "Sean McKeon",  ],
},
{ team:"DEN",
  QB: ["Russell Wilson", "Josh Johnson", "Brett Rypien",  ],
  RB: ["Javonte Williams", "Melvin Gordon III", "Mike Boone", "Devine Ozigbo", "JaQuan Hardy",  ],
  WR: ["Courtland Sutton", "Jerry Jeudy", "KJ Hamler", "Montrell Washington", "Kendall Hinton", "Seth Williams", "Brandon Johnson",  ],
  TE: ["Albert Okwuegbunam", "Greg Dulcich", "Eric Saubert", "Eric Tomlinson", "Andrew Beck", "Dylan Parham",  ],
},
{ team:"DET",
  QB: ["Jared Goff", "Tim Boyle", "David Blough",  ],
  RB: ["D'Andre Swift", "Jamaal Williams", "Justin Jackson", "Craig Reynolds", "Jermar Jefferson", "Godwin Igwebuike",  ],
  WR: ["Amon-Ra St. Brown", "DJ Chark Jr.", "Jameson Williams", "Josh Reynolds", "Quintez Cephus", "Kalif Raymond", "Trinity Benson", "Tom Kennedy", "Devin Funchess", "Kalil Pimpleton",  ],
  TE: ["T.J. Hockenson", "Brock Wright", "James Mitchell", "Shane Zylstra", "Derrick Deese Jr.",  ],
},
{ team:"GB",
  QB: ["Aaron Rodgers", "Jordan Love", "Danny Etling",  ],
  RB: ["Aaron Jones", "AJ Dillon", "Kylin Hill", "Patrick Taylor Jr.", "Tyler Goodson",  ],
  WR: ["Allen Lazard", "Christian Watson", "Romeo Doubs", "Sammy Watkins", "Randall Cobb", "Amari Rodgers", "Travis Fulgham", "Samori Toure", "Juwann Winfree", "Malik Taylor",  ],
  TE: ["Robert Tonyan", "Josiah Deguara", "Marcedes Lewis", "Tyler Davis",  ],
},
{ team:"HOU",
  QB: ["Davis Mills", "Kyle Allen", "Jeff Driskel",  ],
  RB: ["Dameon Pierce", "Marlon Mack", "Rex Burkhead", "Dare Ogunbowale", "Royce Freeman",  ],
  WR: ["Brandin Cooks", "Nico Collins", "Chris Conley", "John Metchie III", "Phillip Dorsett II", "Chris Moore", "Chester Rogers", "Johnny Johnson III", "Jalen Camp", "Drew Estrada",  ],
  TE: ["Brevin Jordan", "Pharaoh Brown", "Antony Auclair", "Teagan Quitoriano", "Seth Green", "Mason Schreck", "Paul Quessenberry",  ],
},
{ team:"IND",
  QB: ["Matt Ryan", "Nick Foles", "Sam Ehlinger", "Jack Coan",  ],
  RB: ["Jonathan Taylor", "Nyheim Hines", "Phillip Lindsay", "Ty'Son Williams", "Deon Jackson", "D'Vonte Price",  ],
  WR: ["Michael Pittman Jr.", "Parris Campbell", "Alec Pierce", "Ashton Dulin", "Mike Strachan", "Dezmon Patmon", "Keke Coutee", "DeMichael Harris",  ],
  TE: ["Mo Alie-Cox", "Jelani Woods", "Kylen Granson", "Michael Jacobson",  ],
},
{ team:"JAC",
  QB: ["Trevor Lawrence", "C.J. Beathard", "E.J. Perry",  ],
  RB: ["Travis Etienne Jr.", "James Robinson", "Snoop Conner", "Ryquell Armstead",  ],
  WR: ["Christian Kirk", "Marvin Jones Jr.", "Laviska Shenault Jr.", "Zay Jones", "Laquon Treadwell", "Jamal Agnew", "Kevin Austin Jr.",  ],
  TE: ["Evan Engram", "Dan Arnold", "Chris Manhertz", "Luke Farrell",  ],
},
{ team:"KC",
  QB: ["Patrick Mahomes II", "Chad Henne", "Shane Buechele",  ],
  RB: ["Clyde Edwards-Helaire", "Ronald Jones II", "Isiah Pacheco", "Jerick McKinnon", "Jerrion Ealy", "Michael Burton",  ],
  WR: ["JuJu Smith-Schuster", "Skyy Moore", "Marquez Valdes-Scantling", "Mecole Hardman", "Justin Watson", "Josh Gordon", "Justyn Ross", "Jody Fortson", "Cornell Powell", "Daurice Fountain",  ],
  TE: ["Travis Kelce", "Noah Gray", "Blake Bell", "Jordan Franks",  ],
},
{ team:"LAC",
  QB: ["Justin Herbert", "Chase Daniel", "Easton Stick",  ],
  RB: ["Austin Ekeler", "Isaiah Spiller", "Joshua Kelley", "Larry Rountree III", "Zander Horvath", "Gabe Nabers", "Leddie Brown", "Kevin Marks Jr.",  ],
  WR: ["Keenan Allen", "Mike Williams", "Joshua Palmer", "Jalen Guyton", "DeAndre Carter", "Joe Reed", "Michael Bandy", "Jason Moore Jr.",  ],
  TE: ["Gerald Everett", "Donald Parham Jr.", "Tre' McKitty", "Stone Smartt",  ],
},
{ team:"LAR",
  QB: ["Matthew Stafford", "John Wolford", "Bryce Perkins",  ],
  RB: ["Cam Akers", "Darrell Henderson Jr.", "Kyren Williams", "Jake Funk",  ],
  WR: ["Cooper Kupp", "Allen Robinson II", "Van Jefferson", "Tutu Atwell", "Ben Skowronek", "Lance McCutcheon", "Brandon Powell", "Landen Akers",  ],
  TE: ["Tyler Higbee", "Jacob Harris", "Brycen Hopkins", "Jared Pinkney", "Roger Carter",  ],
},
{ team:"LV",
  QB: ["Derek Carr", "Jarrett Stidham", "Chase Garbers",  ],
  RB: ["Josh Jacobs", "Zamir White", "Ameer Abdullah", "Brandon Bolden", "Sincere McCormick", "Jakob Johnson", "Brittain Brown",  ],
  WR: ["Davante Adams", "Hunter Renfrow", "Keelan Cole Sr.", "Mack Hollins", "Tyron Johnson", "DJ Turner", "Justin Hall",  ],
  TE: ["Darren Waller", "Foster Moreau", "Jacob Hollister", "Nick Bowers", "Jesper Horsted",  ],
},
{ team:"MIA",
  QB: ["Tua Tagovailoa", "Teddy Bridgewater", "Skylar Thompson", "John Lovett",  ],
  RB: ["Chase Edmonds", "Raheem Mostert", "Sony Michel", "Myles Gaskin", "Salvon Ahmed", "Alec Ingold", "ZaQuandre White", "Gerrid Doaks",  ],
  WR: ["Tyreek Hill", "Jaylen Waddle", "Cedrick Wilson Jr.", "Erik Ezukanma", "Preston Williams", "Trent Sherfield", "Lynn Bowden Jr.", "Mohamed Sanu Sr.",  ],
  TE: ["Mike Gesicki", "Durham Smythe", "Hunter Long", "Cethan Carter",  ],
},
{ team:"MIN",
  QB: ["Kirk Cousins", "Nick Mullens", "Kellen Mond", "Sean Mannion",  ],
  RB: ["Dalvin Cook", "Alexander Mattison", "Kene Nwangwu", "Ty Chandler", "C.J. Ham", "Bryant Koback",  ],
  WR: ["Justin Jefferson", "Adam Thielen", "K.J. Osborn", "Ihmir Smith-Marsette", "Jalen Nailor", "Dan Chisena", "Myron Mitchell", "Trishton Jackson",  ],
  TE: ["Irv Smith Jr.", "Johnny Mundt", "Ben Ellefson", "Zach Davidson",  ],
},
{ team:"NE",
  QB: ["Mac Jones", "Brian Hoyer", "Bailey Zappe",  ],
  RB: ["Damien Harris", "Rhamondre Stevenson", "Pierre Strong Jr.", "Ty Montgomery", "Kevin Harris", "J.J. Taylor",  ],
  WR: ["Jakobi Meyers", "DeVante Parker", "Kendrick Bourne", "Nelson Agholor", "Tyquan Thornton", "Lil'Jordan Humphrey", "Kristian Wilkerson", "Tre Nixon", "Josh Hammond",  ],
  TE: ["Hunter Henry", "Jonnu Smith", "Jalen Wydermyer", "Devin Asiasi", "Matt Sokol",  ],
},
{ team:"NO",
  QB: ["Jameis Winston", "Andy Dalton", "Taysom Hill", "Ian Book",  ],
  RB: ["Alvin Kamara", "Mark Ingram II", "Tony Jones Jr.", "Abram Smith", "Dwayne Washington", "Adam Prentice",  ],
  WR: ["Michael Thomas", "Chris Olave", "Jarvis Landry", "Marquez Callaway", "Tre'Quan Smith", "Deonte Harty", "Kirk Merritt", "Rashid Shaheed",  ],
  TE: ["Adam Trautman", "Juwan Johnson", "Taysom Hill", "Nick Vannett", "J.P. Holtz", "Lucas Krull",  ],
},
{ team:"NYG",
  QB: ["Daniel Jones", "Tyrod Taylor", "Davis Webb",  ],
  RB: ["Saquon Barkley", "Matt Breida", "Gary Brightwell", "Jashaun Corbin", "Antonio Williams", "Sandro Platzgummer",  ],
  WR: ["Kadarius Toney", "Kenny Golladay", "Wan'Dale Robinson", "Sterling Shepard", "Darius Slayton", "Richie James Jr.", "C.J. Board", "Jaylon Moore", "David Sills V", "Alex Bachman", "Marcus Kemp", "Travis Toivonen",  ],
  TE: ["Daniel Bellinger", "Jordan Akins", "Chris Myarick", "Austin Allen",  ],
},
{ team:"NYJ",
  QB: ["Zach Wilson", "Joe Flacco", "Mike White",  ],
  RB: ["Breece Hall", "Michael Carter", "Ty Johnson", "Tevin Coleman", "Zonovan Knight", "La'Mical Perine", "Nick Bawden", "Zonovan Knight",  ],
  WR: ["Elijah Moore", "Garrett Wilson", "Corey Davis", "Braxton Berrios", "Denzel Mims", "Jeff Smith", "Lawrence Cager", "Tarik Black",  ],
  TE: ["C.J. Uzomah", "Tyler Conklin", "Jeremy Ruckert", "Trevon Wesco", "Kenny Yeboah",  ],
},
{ team:"PHI",
  QB: ["Jalen Hurts", "Gardner Minshew II", "Carson Strong", "Reid Sinnett",  ],
  RB: ["Miles Sanders", "Kenneth Gainwell", "Boston Scott", "Kennedy Brooks", "Jason Huntley",  ],
  WR: ["A.J. Brown", "DeVonta Smith", "Quez Watkins", "Jalen Reagor", "Zach Pascal", "Greg Ward", "Deon Cain", "Britain Covey", "Devon Allen", "John Hightower",  ],
  TE: ["Dallas Goedert", "Grant Calcaterra", "Tyree Jackson", "Jack Stoll", "Richard Rodgers", "Noah Togiai",  ],
},
{ team:"PIT",
  QB: ["Mitch Trubisky", "Kenny Pickett", "Mason Rudolph",  ],
  RB: ["Najee Harris", "Jaylen Warren", "Benny Snell Jr.", "Anthony McFarland Jr.", "Jeremy McNichols", "Derek Watt", "Max Borghi",  ],
  WR: ["Diontae Johnson", "Chase Claypool", "George Pickens", "Calvin Austin III", "Miles Boykin", "Gunner Olszewski", "Steven Sims Jr.", "Tyler Vaughns", "Cody White",  ],
  TE: ["Pat Freiermuth", "Zach Gentry", "Connor Heyward", "Kevin Rader", "Jace Sternberger",  ],
},
{ team:"SEA",
  QB: ["Drew Lock", "Geno Smith", "Jacob Eason",  ],
  RB: ["Rashaad Penny", "Ken Walker III", "DeeJay Dallas", "Travis Homer", "Darwin Thompson", "Josh Johnson", "Ronnie Rivers",  ],
  WR: ["DK Metcalf", "Tyler Lockett", "Dee Eskridge", "Freddie Swain", "Bo Melton", "Marquise Goodwin", "Penny Hart", "Dareke Young", "J.J. Arcega-Whiteside", "Cody Thompson",  ],
  TE: ["Noah Fant", "Will Dissly", "Colby Parkinson", "Tyler Mabry",  ],
},
{ team:"SF",
  QB: ["Trey Lance", "Jimmy Garoppolo", "Nate Sudfeld", "Brock Purdy",  ],
  RB: ["Elijah Mitchell", "Tyrion Davis-Price", "Jeff Wilson Jr.", "Trey Sermon", "Kyle Juszczyk", "JaMycal Hasty", "Jordan Mason",  ],
  WR: ["Deebo Samuel", "Brandon Aiyuk", "Danny Gray", "Jauan Jennings", "Ray-Ray McCloud", "Marcus Johnson", "Malik Turner",  ],
  TE: ["George Kittle", "Ross Dwelley", "Tyler Kroft", "Charlie Woerner",  ],
},
{ team:"TB",
  QB: ["Tom Brady", "Kyle Trask", "Blaine Gabbert", "Ryan Griffin",  ],
  RB: ["Leonard Fournette", "Rachaad White", "Ke'Shawn Vaughn", "Giovani Bernard", "Kenjon Barner", "Patrick Laird",  ],
  WR: ["Mike Evans", "Chris Godwin", "Russell Gage", "Julio Jones", "Tyler Johnson", "Breshad Perriman", "Jaelon Darden", "Scotty Miller", "Deven Thompkins",  ],
  TE: ["Cameron Brate", "Kyle Rudolph", "Cade Otton", "Ko Kieft", "JJ Howland",  ],
},
{ team:"TEN",
  QB: ["Ryan Tannehill", "Malik Willis", "Logan Woodside",  ],
  RB: ["Derrick Henry", "Hassan Haskins", "Dontrell Hilliard", "Julius Chestnut", "Tory Carter", "Javian Hawkins", "Trenton Cannon",  ],
  WR: ["Robert Woods", "Treylon Burks", "Nick Westbrook-Ikhine", "Kyle Philips", "Dez Fitzpatrick", "Racey McMath", "Cody Hollister", "Reggie Roberson Jr.",  ],
  TE: ["Austin Hooper", "Chigoziem Okonkwo", "Geoff Swaim", "Tommy Hudson", "David Wells",  ],
},
{ team:"WAS",
  QB: ["Carson Wentz", "Sam Howell", "Taylor Heinicke",  ],
  RB: ["Antonio Gibson", "Brian Robinson Jr.", "J.D. McKissic", "Jaret Patterson", "Jonathan Williams",  ],
  WR: ["Terry McLaurin", "Jahan Dotson", "Curtis Samuel", "Dyami Brown", "Cam Sims", "Dax Milne", "Alex Erickson", "Marken Michel", "Kyric McGowan",  ],
  TE: ["Logan Thomas", "John Bates", "Cole Turner", "Kendall Blanton", "Armani Rogers", "Eli Wolf", "Curtis Hodges",  ],
},
]
